-- ============================================================================
-- Subqueries - PostgreSQL 18
-- ============================================================================
-- Source: Migrated from comparison_operators_advanced_tdd.rs, comparison_operators_extreme_edge_cases_tdd.rs
-- Description: Subqueries in SELECT, WHERE, and FROM clauses
--
-- PostgreSQL: Full support
-- BigQuery: Limited or no support
-- SQL Standard: PostgreSQL 18 specific
-- ============================================================================

DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'user@example.com');
INSERT INTO users VALUES (2, 'USER@EXAMPLE.COM');
INSERT INTO users VALUES (3, 'user@test.org');
DROP TABLE IF EXISTS paths;
CREATE TABLE paths (id INT64, path STRING);
INSERT INTO paths VALUES (1, '/home/user/file.txt');
INSERT INTO paths VALUES (2, '/HOME/USER/FILE.TXT');
INSERT INTO paths VALUES (3, '/var/log/system.log');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC123');
INSERT INTO data VALUES (2, 'XYZ789');
INSERT INTO data VALUES (3, 'ABC');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, category STRING);
INSERT INTO products VALUES (1, 'Electronics');
INSERT INTO products VALUES (2, 'Furniture');
INSERT INTO products VALUES (3, 'Clothing');
INSERT INTO products VALUES (4, 'Food');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AB');
INSERT INTO codes VALUES (3, 'ABB');
INSERT INTO codes VALUES (4, 'ABBB');
INSERT INTO codes VALUES (5, 'AC');
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM users WHERE email NOT ILIKE '%EXAMPLE.COM%' ORDER BY id;
SELECT id FROM paths WHERE path ILIKE '/HOME/%' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC[0-9]+' ORDER BY id;
SELECT id FROM products WHERE category SIMILAR TO 'Electronics|Furniture' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'AB*' ORDER BY id;
SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_ilike_special_characters
-- Source: comparison_operators_advanced_tdd.rs:209
-- ============================================================================
DROP TABLE IF EXISTS paths;
CREATE TABLE paths (id INT64, path STRING);
INSERT INTO paths VALUES (1, '/home/user/file.txt');
INSERT INTO paths VALUES (2, '/HOME/USER/FILE.TXT');
INSERT INTO paths VALUES (3, '/var/log/system.log');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC123');
INSERT INTO data VALUES (2, 'XYZ789');
INSERT INTO data VALUES (3, 'ABC');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, category STRING);
INSERT INTO products VALUES (1, 'Electronics');
INSERT INTO products VALUES (2, 'Furniture');
INSERT INTO products VALUES (3, 'Clothing');
INSERT INTO products VALUES (4, 'Food');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AB');
INSERT INTO codes VALUES (3, 'ABB');
INSERT INTO codes VALUES (4, 'ABBB');
INSERT INTO codes VALUES (5, 'AC');
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM paths WHERE path ILIKE '/HOME/%' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC[0-9]+' ORDER BY id;
SELECT id FROM products WHERE category SIMILAR TO 'Electronics|Furniture' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'AB*' ORDER BY id;
SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_basic_pattern
-- Source: comparison_operators_advanced_tdd.rs:239
-- ============================================================================
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC123');
INSERT INTO data VALUES (2, 'XYZ789');
INSERT INTO data VALUES (3, 'ABC');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, category STRING);
INSERT INTO products VALUES (1, 'Electronics');
INSERT INTO products VALUES (2, 'Furniture');
INSERT INTO products VALUES (3, 'Clothing');
INSERT INTO products VALUES (4, 'Food');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AB');
INSERT INTO codes VALUES (3, 'ABB');
INSERT INTO codes VALUES (4, 'ABBB');
INSERT INTO codes VALUES (5, 'AC');
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM data WHERE code SIMILAR TO 'ABC[0-9]+' ORDER BY id;
SELECT id FROM products WHERE category SIMILAR TO 'Electronics|Furniture' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'AB*' ORDER BY id;
SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_alternation
-- Source: comparison_operators_advanced_tdd.rs:263
-- ============================================================================
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, category STRING);
INSERT INTO products VALUES (1, 'Electronics');
INSERT INTO products VALUES (2, 'Furniture');
INSERT INTO products VALUES (3, 'Clothing');
INSERT INTO products VALUES (4, 'Food');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AB');
INSERT INTO codes VALUES (3, 'ABB');
INSERT INTO codes VALUES (4, 'ABBB');
INSERT INTO codes VALUES (5, 'AC');
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM products WHERE category SIMILAR TO 'Electronics|Furniture' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'AB*' ORDER BY id;
SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_quantifiers
-- Source: comparison_operators_advanced_tdd.rs:292
-- ============================================================================
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AB');
INSERT INTO codes VALUES (3, 'ABB');
INSERT INTO codes VALUES (4, 'ABBB');
INSERT INTO codes VALUES (5, 'AC');
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM codes WHERE code SIMILAR TO 'AB*' ORDER BY id;
SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_character_classes
-- Source: comparison_operators_advanced_tdd.rs:323
-- ============================================================================
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INT64, identifier STRING);
INSERT INTO ids VALUES (1, 'ABC123');
INSERT INTO ids VALUES (2, 'XYZ456');
INSERT INTO ids VALUES (3, 'ABC');
INSERT INTO ids VALUES (4, '123456');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM ids WHERE identifier SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9]' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_anchoring
-- Source: comparison_operators_advanced_tdd.rs:351
-- ============================================================================
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, 'hello world');
INSERT INTO data VALUES (3, 'say hello');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM data WHERE text SIMILAR TO 'hello' ORDER BY id;
SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_wildcard_percent
-- Source: comparison_operators_advanced_tdd.rs:375
-- ============================================================================
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING);
INSERT INTO users VALUES (1, 'alice@example.com');
INSERT INTO users VALUES (2, 'bob@example.com');
INSERT INTO users VALUES (3, 'charlie@test.org');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM users WHERE email SIMILAR TO '%@example.com' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_wildcard_underscore
-- Source: comparison_operators_advanced_tdd.rs:399
-- ============================================================================
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A1');
INSERT INTO codes VALUES (2, 'A12');
INSERT INTO codes VALUES (3, 'B1');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM codes WHERE code SIMILAR TO '_1' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_escape_clause
-- Source: comparison_operators_advanced_tdd.rs:423
-- ============================================================================
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '50%');
INSERT INTO data VALUES (2, '50percent');
INSERT INTO data VALUES (3, '100%');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM data WHERE text SIMILAR TO '50!%' ESCAPE '!' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_null_handling
-- Source: comparison_operators_advanced_tdd.rs:448
-- ============================================================================
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, 'hello');
INSERT INTO data VALUES (2, NULL);
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM data WHERE text SIMILAR TO 'h%' ORDER BY id;
SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_not_similar_to
-- Source: comparison_operators_advanced_tdd.rs:469
-- ============================================================================
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'document.pdf');
INSERT INTO files VALUES (2, 'image.jpg');
INSERT INTO files VALUES (3, 'data.csv');
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM files WHERE filename NOT SIMILAR TO '%.pdf' ORDER BY id;
SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_complex_email_pattern
-- Source: comparison_operators_advanced_tdd.rs:493
-- ============================================================================
DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts (id INT64, email STRING);
INSERT INTO contacts VALUES (1, 'user@example.com');
INSERT INTO contacts VALUES (2, 'invalid.email');
INSERT INTO contacts VALUES (3, 'test@test.org');
INSERT INTO contacts VALUES (4, '@invalid.com');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM contacts WHERE email SIMILAR TO '%[a-z0-9]+@[a-z0-9]+\.[a-z][a-z]+' ORDER BY id;
SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_case_sensitive
-- Source: comparison_operators_advanced_tdd.rs:521
-- ============================================================================
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, code STRING);
INSERT INTO data VALUES (1, 'ABC');
INSERT INTO data VALUES (2, 'abc');
INSERT INTO data VALUES (3, 'AbC');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM data WHERE code SIMILAR TO 'ABC' ORDER BY id;
SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_repetition_range
-- Source: comparison_operators_advanced_tdd.rs:545
-- ============================================================================
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (id INT64, code STRING);
INSERT INTO codes VALUES (1, 'A');
INSERT INTO codes VALUES (2, 'AA');
INSERT INTO codes VALUES (3, 'AAA');
INSERT INTO codes VALUES (4, 'AAAA');
INSERT INTO codes VALUES (5, 'AAAAA');
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM codes WHERE code SIMILAR TO 'A{2,4}' ORDER BY id;
SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_ilike_with_and_or
-- Source: comparison_operators_advanced_tdd.rs:580
-- ============================================================================
DROP TABLE IF EXISTS products;
CREATE TABLE products (id INT64, name STRING, category STRING);
INSERT INTO products VALUES (1, 'Laptop Dell', 'Electronics');
INSERT INTO products VALUES (2, 'LAPTOP HP', 'Electronics');
INSERT INTO products VALUES (3, 'Chair Oak', 'Furniture');
INSERT INTO products VALUES (4, 'laptop Lenovo', 'Electronics');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM products WHERE name ILIKE '%laptop%' AND category = 'Electronics' ORDER BY id;
SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_with_in_clause
-- Source: comparison_operators_advanced_tdd.rs:607
-- ============================================================================
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING, type STRING);
INSERT INTO files VALUES (1, 'doc1.pdf', 'document');
INSERT INTO files VALUES (2, 'img1.jpg', 'image');
INSERT INTO files VALUES (3, 'doc2.pdf', 'document');
INSERT INTO files VALUES (4, 'data.csv', 'data');
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT id FROM files WHERE filename SIMILAR TO 'doc[0-9]+.pdf' AND type IN ('document', 'archive') ORDER BY id;
SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_ilike_in_subquery
-- Source: comparison_operators_advanced_tdd.rs:634
-- ============================================================================
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT64, email STRING, verified BOOL);
INSERT INTO users VALUES (1, 'alice@EXAMPLE.com', true);
INSERT INTO users VALUES (2, 'bob@EXAMPLE.com', false);
INSERT INTO users VALUES (3, 'charlie@test.org', true);
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (order_id INT64, user_id INT64, amount FLOAT64);
INSERT INTO orders VALUES (101, 1, 100.0);
INSERT INTO orders VALUES (102, 3, 200.0);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'EMP[0-9]+');
DROP TABLE IF EXISTS codes;
CREATE TABLE codes (code_id INT64, code STRING);
INSERT INTO codes VALUES (1, 'EMP001');
INSERT INTO codes VALUES (2, 'EMP002');
INSERT INTO codes VALUES (3, 'MGR001');
DROP TABLE IF EXISTS files;
CREATE TABLE files (id INT64, filename STRING);
INSERT INTO files VALUES (1, 'report.PDF');
INSERT INTO files VALUES (2, 'image.JPG');
INSERT INTO files VALUES (3, 'data.CSV');
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (id INT64, message STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
INSERT INTO data VALUES (1, '');
INSERT INTO data VALUES (2, 'hello');
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS data;
CREATE TABLE data (id INT64, text STRING);
DROP TABLE IF EXISTS names;
CREATE TABLE names (id INT64, name STRING);
INSERT INTO names VALUES (1, 'café');
INSERT INTO names VALUES (2, 'cafe\u{0301}');

SELECT order_id FROM orders WHERE user_id IN (SELECT id FROM users WHERE email ILIKE '%example.com%') ORDER BY order_id;
SELECT c.code_id FROM codes c, patterns p WHERE c.code SIMILAR TO p.pattern ORDER BY c.code_id;
SELECT id, CASE WHEN filename ILIKE '%.pdf' THEN 'Document' WHEN filename ILIKE '%.jpg' THEN 'Image' ELSE 'Other' END as file_type FROM files ORDER BY id;
SELECT id FROM logs WHERE message ILIKE '%needle%';
SELECT id FROM data WHERE text SIMILAR TO '' ORDER BY id;
SELECT id FROM data WHERE text SIMILAR TO '[a-z';
SELECT id FROM data WHERE text SIMILAR TO '%test%' ESCAPE 'AB';
SELECT id FROM names WHERE name ILIKE 'café' ORDER BY id;

-- ============================================================================
-- Test: test_similar_to_with_subquery
-- Source: comparison_operators_extreme_edge_cases_tdd.rs:1007
-- ============================================================================
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (id INT64, pattern STRING);
INSERT INTO patterns VALUES (1, 'a%');
DROP TABLE IF EXISTS strings;
CREATE TABLE strings (id INT64, str STRING);
INSERT INTO strings VALUES (1, 'apple');
INSERT INTO strings VALUES (2, 'banana');
DROP TABLE IF EXISTS t;
CREATE TABLE t (id INT64, str STRING);
INSERT INTO t VALUES (1, 'hello world');
INSERT INTO t VALUES (2, 'hello');
INSERT INTO t VALUES (3, 'world');

SELECT id FROM strings WHERE str SIMILAR TO (SELECT pattern FROM patterns WHERE id = 1);
SELECT id FROM t WHERE str ~ 'hello' AND str ~ 'world';
