-- ============================================================================
-- Subqueries - GoogleSQL/BigQuery
-- ============================================================================
-- Source: Migrated from insert_enhancements_comprehensive_tdd.rs
-- Description: Subqueries in SELECT, WHERE, and FROM clauses
--
-- PostgreSQL: Limited or no support
-- BigQuery: Full support
-- SQL Standard: GoogleSQL/BigQuery specific
-- ============================================================================

DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b STRING, c FLOAT64);
INSERT INTO test VALUES (NULL, NULL, NULL), (1, 'x', 1.5);
DROP TABLE IF EXISTS source;
CREATE TABLE source (score INT64);
DROP TABLE IF EXISTS graded;
CREATE TABLE graded (grade STRING);
INSERT INTO source VALUES (95), (75), (55);
INSERT INTO graded SELECT CASE WHEN score >= 90 THEN 'A' WHEN score >= 70 THEN 'B' ELSE 'C' END FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (name STRING);
DROP TABLE IF EXISTS processed;
CREATE TABLE processed (upper_name STRING, len INT64);
INSERT INTO source VALUES ('alice'), ('bob'), ('charlie');
INSERT INTO processed SELECT UPPER(name), LENGTH(name) FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (id INT64, value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (id INT64, safe_value INT64);
INSERT INTO source VALUES (1, 100), (2, NULL), (3, 300);
INSERT INTO dest SELECT id, CASE WHEN value IS NULL THEN 0 ELSE value END FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (value FLOAT64);
INSERT INTO test VALUES (1.0), (-1.0), (0.0);
DROP TABLE IF EXISTS source;
CREATE TABLE source (value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (value INT64);
INSERT INTO source VALUES (1), (2), (2), (3), (3), (3);
INSERT INTO dest SELECT DISTINCT value FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (id INT64, name STRING, age INT64, active BOOL);
INSERT INTO test (id, name) VALUES (1, 'Alice'), (2, 'Bob');
INSERT INTO nonexistent VALUES (1);
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64, b INT64, c INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (text STRING);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (num INT64);
INSERT INTO source VALUES ('not a number');
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test VALUES (1, 2), (3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64, c INT64);
INSERT INTO test (a, b) VALUES (1, 2, 3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, z) VALUES (1, 2);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, a) VALUES (1, 2);
DROP TABLE IF EXISTS raw_events;
CREATE TABLE raw_events ( event_id INT64, event_type STRING, value INT64, timestamp INT64 );
DROP TABLE IF EXISTS processed_events;
CREATE TABLE processed_events ( id INT64, category STRING, amount INT64 );
INSERT INTO raw_events VALUES (1, 'purchase', 100, 1000), (2, 'refund', -50, 1001), (3, 'purchase', 200, 1002);
INSERT INTO processed_events SELECT event_id, UPPER(event_type), value FROM raw_events WHERE event_type = 'purchase' AND value > 0;
DROP TABLE IF EXISTS users_old;
CREATE TABLE users_old ( user_id INT64, first_name STRING, last_name STRING );
DROP TABLE IF EXISTS users_new;
CREATE TABLE users_new ( id INT64, full_name STRING );
INSERT INTO users_old VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
INSERT INTO users_new SELECT user_id, CONCAT(first_name, ' ', last_name) FROM users_old;
DROP TABLE IF EXISTS products;
CREATE TABLE products ( id INT64, name STRING, price FLOAT64, in_stock BOOL );
INSERT INTO products VALUES (1, 'Widget', 19.99, true), (2, 'Gadget', 29.99, true), (3, 'Doohickey', 9.99, false), (4, 'Thingamajig', 39.99, true);
DROP TABLE IF EXISTS staging;
CREATE TABLE staging (id INT64, version INT64, data STRING);
DROP TABLE IF EXISTS production;
CREATE TABLE production (id INT64, version INT64, data STRING);
INSERT INTO production VALUES (1, 1, 'v1'), (2, 1, 'v1');
INSERT INTO staging VALUES (1, 2, 'v2'), (2, 1, 'v1'), (3, 1, 'new');
INSERT INTO production SELECT s.id, s.version, s.data FROM staging s WHERE NOT EXISTS ( SELECT 1 FROM production p WHERE p.id = s.id AND p.version >= s.version );
DROP TABLE IF EXISTS config;
CREATE TABLE config ( key STRING, value STRING, updated_at INT64 );
INSERT INTO config VALUES ('theme', 'dark', 1000);
INSERT INTO config (key, value) VALUES ('language', 'en');

SELECT * FROM test;
SELECT grade FROM graded ORDER BY grade;
SELECT age, active FROM test WHERE id = 1;
SELECT updated_at FROM config WHERE key = 'language';

-- ============================================================================
-- Test: test_insert_select_with_case_expression
-- Source: insert_enhancements_comprehensive_tdd.rs:1086
-- ============================================================================
DROP TABLE IF EXISTS source;
CREATE TABLE source (score INT64);
DROP TABLE IF EXISTS graded;
CREATE TABLE graded (grade STRING);
INSERT INTO source VALUES (95), (75), (55);
INSERT INTO graded SELECT CASE WHEN score >= 90 THEN 'A' WHEN score >= 70 THEN 'B' ELSE 'C' END FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (name STRING);
DROP TABLE IF EXISTS processed;
CREATE TABLE processed (upper_name STRING, len INT64);
INSERT INTO source VALUES ('alice'), ('bob'), ('charlie');
INSERT INTO processed SELECT UPPER(name), LENGTH(name) FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (id INT64, value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (id INT64, safe_value INT64);
INSERT INTO source VALUES (1, 100), (2, NULL), (3, 300);
INSERT INTO dest SELECT id, CASE WHEN value IS NULL THEN 0 ELSE value END FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (value FLOAT64);
INSERT INTO test VALUES (1.0), (-1.0), (0.0);
DROP TABLE IF EXISTS source;
CREATE TABLE source (value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (value INT64);
INSERT INTO source VALUES (1), (2), (2), (3), (3), (3);
INSERT INTO dest SELECT DISTINCT value FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (id INT64, name STRING, age INT64, active BOOL);
INSERT INTO test (id, name) VALUES (1, 'Alice'), (2, 'Bob');
INSERT INTO nonexistent VALUES (1);
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64, b INT64, c INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (text STRING);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (num INT64);
INSERT INTO source VALUES ('not a number');
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test VALUES (1, 2), (3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64, c INT64);
INSERT INTO test (a, b) VALUES (1, 2, 3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, z) VALUES (1, 2);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, a) VALUES (1, 2);
DROP TABLE IF EXISTS raw_events;
CREATE TABLE raw_events ( event_id INT64, event_type STRING, value INT64, timestamp INT64 );
DROP TABLE IF EXISTS processed_events;
CREATE TABLE processed_events ( id INT64, category STRING, amount INT64 );
INSERT INTO raw_events VALUES (1, 'purchase', 100, 1000), (2, 'refund', -50, 1001), (3, 'purchase', 200, 1002);
INSERT INTO processed_events SELECT event_id, UPPER(event_type), value FROM raw_events WHERE event_type = 'purchase' AND value > 0;
DROP TABLE IF EXISTS users_old;
CREATE TABLE users_old ( user_id INT64, first_name STRING, last_name STRING );
DROP TABLE IF EXISTS users_new;
CREATE TABLE users_new ( id INT64, full_name STRING );
INSERT INTO users_old VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
INSERT INTO users_new SELECT user_id, CONCAT(first_name, ' ', last_name) FROM users_old;
DROP TABLE IF EXISTS products;
CREATE TABLE products ( id INT64, name STRING, price FLOAT64, in_stock BOOL );
INSERT INTO products VALUES (1, 'Widget', 19.99, true), (2, 'Gadget', 29.99, true), (3, 'Doohickey', 9.99, false), (4, 'Thingamajig', 39.99, true);
DROP TABLE IF EXISTS staging;
CREATE TABLE staging (id INT64, version INT64, data STRING);
DROP TABLE IF EXISTS production;
CREATE TABLE production (id INT64, version INT64, data STRING);
INSERT INTO production VALUES (1, 1, 'v1'), (2, 1, 'v1');
INSERT INTO staging VALUES (1, 2, 'v2'), (2, 1, 'v1'), (3, 1, 'new');
INSERT INTO production SELECT s.id, s.version, s.data FROM staging s WHERE NOT EXISTS ( SELECT 1 FROM production p WHERE p.id = s.id AND p.version >= s.version );
DROP TABLE IF EXISTS config;
CREATE TABLE config ( key STRING, value STRING, updated_at INT64 );
INSERT INTO config VALUES ('theme', 'dark', 1000);
INSERT INTO config (key, value) VALUES ('language', 'en');

SELECT grade FROM graded ORDER BY grade;
SELECT age, active FROM test WHERE id = 1;
SELECT updated_at FROM config WHERE key = 'language';

-- ============================================================================
-- Test: test_insert_select_with_string_functions
-- Source: insert_enhancements_comprehensive_tdd.rs:1118
-- ============================================================================
DROP TABLE IF EXISTS source;
CREATE TABLE source (name STRING);
DROP TABLE IF EXISTS processed;
CREATE TABLE processed (upper_name STRING, len INT64);
INSERT INTO source VALUES ('alice'), ('bob'), ('charlie');
INSERT INTO processed SELECT UPPER(name), LENGTH(name) FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (id INT64, value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (id INT64, safe_value INT64);
INSERT INTO source VALUES (1, 100), (2, NULL), (3, 300);
INSERT INTO dest SELECT id, CASE WHEN value IS NULL THEN 0 ELSE value END FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (value FLOAT64);
INSERT INTO test VALUES (1.0), (-1.0), (0.0);
DROP TABLE IF EXISTS source;
CREATE TABLE source (value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (value INT64);
INSERT INTO source VALUES (1), (2), (2), (3), (3), (3);
INSERT INTO dest SELECT DISTINCT value FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (id INT64, name STRING, age INT64, active BOOL);
INSERT INTO test (id, name) VALUES (1, 'Alice'), (2, 'Bob');
INSERT INTO nonexistent VALUES (1);
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64, b INT64, c INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (text STRING);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (num INT64);
INSERT INTO source VALUES ('not a number');
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test VALUES (1, 2), (3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64, c INT64);
INSERT INTO test (a, b) VALUES (1, 2, 3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, z) VALUES (1, 2);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, a) VALUES (1, 2);
DROP TABLE IF EXISTS raw_events;
CREATE TABLE raw_events ( event_id INT64, event_type STRING, value INT64, timestamp INT64 );
DROP TABLE IF EXISTS processed_events;
CREATE TABLE processed_events ( id INT64, category STRING, amount INT64 );
INSERT INTO raw_events VALUES (1, 'purchase', 100, 1000), (2, 'refund', -50, 1001), (3, 'purchase', 200, 1002);
INSERT INTO processed_events SELECT event_id, UPPER(event_type), value FROM raw_events WHERE event_type = 'purchase' AND value > 0;
DROP TABLE IF EXISTS users_old;
CREATE TABLE users_old ( user_id INT64, first_name STRING, last_name STRING );
DROP TABLE IF EXISTS users_new;
CREATE TABLE users_new ( id INT64, full_name STRING );
INSERT INTO users_old VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
INSERT INTO users_new SELECT user_id, CONCAT(first_name, ' ', last_name) FROM users_old;
DROP TABLE IF EXISTS products;
CREATE TABLE products ( id INT64, name STRING, price FLOAT64, in_stock BOOL );
INSERT INTO products VALUES (1, 'Widget', 19.99, true), (2, 'Gadget', 29.99, true), (3, 'Doohickey', 9.99, false), (4, 'Thingamajig', 39.99, true);
DROP TABLE IF EXISTS staging;
CREATE TABLE staging (id INT64, version INT64, data STRING);
DROP TABLE IF EXISTS production;
CREATE TABLE production (id INT64, version INT64, data STRING);
INSERT INTO production VALUES (1, 1, 'v1'), (2, 1, 'v1');
INSERT INTO staging VALUES (1, 2, 'v2'), (2, 1, 'v1'), (3, 1, 'new');
INSERT INTO production SELECT s.id, s.version, s.data FROM staging s WHERE NOT EXISTS ( SELECT 1 FROM production p WHERE p.id = s.id AND p.version >= s.version );
DROP TABLE IF EXISTS config;
CREATE TABLE config ( key STRING, value STRING, updated_at INT64 );
INSERT INTO config VALUES ('theme', 'dark', 1000);
INSERT INTO config (key, value) VALUES ('language', 'en');

SELECT age, active FROM test WHERE id = 1;
SELECT updated_at FROM config WHERE key = 'language';

-- ============================================================================
-- Test: test_insert_select_with_coalesce
-- Source: insert_enhancements_comprehensive_tdd.rs:1146
-- ============================================================================
DROP TABLE IF EXISTS source;
CREATE TABLE source (id INT64, value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (id INT64, safe_value INT64);
INSERT INTO source VALUES (1, 100), (2, NULL), (3, 300);
INSERT INTO dest SELECT id, CASE WHEN value IS NULL THEN 0 ELSE value END FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (value FLOAT64);
INSERT INTO test VALUES (1.0), (-1.0), (0.0);
DROP TABLE IF EXISTS source;
CREATE TABLE source (value INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (value INT64);
INSERT INTO source VALUES (1), (2), (2), (3), (3), (3);
INSERT INTO dest SELECT DISTINCT value FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (id INT64, name STRING, age INT64, active BOOL);
INSERT INTO test (id, name) VALUES (1, 'Alice'), (2, 'Bob');
INSERT INTO nonexistent VALUES (1);
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64, b INT64, c INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (a INT64);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (x INT64, y INT64);
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS source;
CREATE TABLE source (text STRING);
DROP TABLE IF EXISTS dest;
CREATE TABLE dest (num INT64);
INSERT INTO source VALUES ('not a number');
INSERT INTO dest SELECT * FROM source;
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test VALUES (1, 2), (3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64, c INT64);
INSERT INTO test (a, b) VALUES (1, 2, 3);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, z) VALUES (1, 2);
DROP TABLE IF EXISTS test;
CREATE TABLE test (a INT64, b INT64);
INSERT INTO test (a, a) VALUES (1, 2);
DROP TABLE IF EXISTS raw_events;
CREATE TABLE raw_events ( event_id INT64, event_type STRING, value INT64, timestamp INT64 );
DROP TABLE IF EXISTS processed_events;
CREATE TABLE processed_events ( id INT64, category STRING, amount INT64 );
INSERT INTO raw_events VALUES (1, 'purchase', 100, 1000), (2, 'refund', -50, 1001), (3, 'purchase', 200, 1002);
INSERT INTO processed_events SELECT event_id, UPPER(event_type), value FROM raw_events WHERE event_type = 'purchase' AND value > 0;
DROP TABLE IF EXISTS users_old;
CREATE TABLE users_old ( user_id INT64, first_name STRING, last_name STRING );
DROP TABLE IF EXISTS users_new;
CREATE TABLE users_new ( id INT64, full_name STRING );
INSERT INTO users_old VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
INSERT INTO users_new SELECT user_id, CONCAT(first_name, ' ', last_name) FROM users_old;
DROP TABLE IF EXISTS products;
CREATE TABLE products ( id INT64, name STRING, price FLOAT64, in_stock BOOL );
INSERT INTO products VALUES (1, 'Widget', 19.99, true), (2, 'Gadget', 29.99, true), (3, 'Doohickey', 9.99, false), (4, 'Thingamajig', 39.99, true);
DROP TABLE IF EXISTS staging;
CREATE TABLE staging (id INT64, version INT64, data STRING);
DROP TABLE IF EXISTS production;
CREATE TABLE production (id INT64, version INT64, data STRING);
INSERT INTO production VALUES (1, 1, 'v1'), (2, 1, 'v1');
INSERT INTO staging VALUES (1, 2, 'v2'), (2, 1, 'v1'), (3, 1, 'new');
INSERT INTO production SELECT s.id, s.version, s.data FROM staging s WHERE NOT EXISTS ( SELECT 1 FROM production p WHERE p.id = s.id AND p.version >= s.version );
DROP TABLE IF EXISTS config;
CREATE TABLE config ( key STRING, value STRING, updated_at INT64 );
INSERT INTO config VALUES ('theme', 'dark', 1000);
INSERT INTO config (key, value) VALUES ('language', 'en');

SELECT age, active FROM test WHERE id = 1;
SELECT updated_at FROM config WHERE key = 'language';
