#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum FunctionName {
    Count,
    Sum,
    Avg,
    Average,
    Min,
    Minimum,
    Max,
    Maximum,

    StringAgg,
    GroupConcat,
    ListAgg,
    ArrayAgg,
    Collect,

    StddevPop,
    Stddevp,
    StddevSamp,
    Stddevs,
    Stddev,
    Stdev,
    StandardDeviation,
    VarPop,
    Varp,
    VarSamp,
    Vars,
    Variance,
    Var,
    Median,
    PercentileCont,
    PercentileDisc,
    Mode,
    Corr,
    CovarPop,
    CovarSamp,
    CountIf,

    ApproxCountDistinct,
    ApproxDistinct,
    ApproxQuantiles,
    ApproxTopCount,
    ApproxTopSum,
    Ndv,

    Upper,
    Ucase,
    Lower,
    Lcase,
    Trim,
    Btrim,
    Ltrim,
    TrimLeft,
    Rtrim,
    TrimRight,
    Concat,
    Concatenate,
    Substring,
    Substr,
    Mid,
    Length,
    Len,
    CharLength,
    CharacterLength,
    OctetLength,
    Lengthb,
    Position,
    Strpos,
    Instr,
    Locate,
    Replace,
    StrReplace,
    Split,
    SplitPart,
    StringSplit,
    Reverse,
    Strrev,
    Repeat,
    Replicate,
    Left,
    Right,
    Lpad,
    LeftPad,
    Rpad,
    RightPad,
    Ascii,
    Ord,
    Chr,
    Char,
    Initcap,
    Proper,
    Translate,

    Abs,
    Absolute,
    Ceil,
    Ceiling,
    Floor,
    Round,
    Rnd,
    Trunc,
    Truncate,
    Sqrt,
    Sqr,
    Pow,
    Power,
    Exp,
    Exponent,
    Ln,
    Loge,
    Log,
    Logarithm,
    Log10,
    Log2,
    Sign,
    Signum,
    Mod,
    Modulo,
    Div,
    Intdiv,
    Random,
    Rand,
    Pi,

    Sin,
    Sine,
    Cos,
    Cosine,
    Tan,
    Tangent,
    Asin,
    Arcsine,
    Acos,
    Arccosine,
    Atan,
    Arctangent,
    Atan2,
    Arctangent2,

    CurrentDate,
    Curdate,
    Today,
    CurrentTime,
    Curtime,
    CurrentTimestamp,
    Getdate,
    Sysdate,
    Systimestamp,
    Now,
    Localtime,
    Localtimestamp,
    Extract,
    DateTrunc,
    TruncDate,
    DatePart,
    Datepart,
    DateAdd,
    Dateadd,
    Adddate,
    DateSub,
    Datesub,
    Subdate,
    DateDiff,
    Datediff,
    Timestampdiff,
    Age,
    ToTimestamp,
    StrToDate,
    ParseDatetime,
    Timestamp,
    ToDate,
    Date,
    CastDate,
    FormatTimestamp,
    DateFormat,
    ToChar,

    Coalesce,
    Nullif,
    Ifnull,
    Nvl,
    Isnull,
    If,
    Iif,
    Greatest,
    MaxValue,
    Least,
    MinValue,

    Cast,
    TryCast,
    Trycast,
    SafeCast,
    Safecast,

    JsonExtract,
    JsonExtractScalar,
    JsonValue,
    JsonExtractString,
    JsonQuery,
    JsonArrayLength,
    JsonLength,
    JsonTypeof,
    JsonType,

    ArrayLength,
    Cardinality,
    ArrayConcat,
    ArrayCat,
    ArrayContains,
    ArrayContainsAll,
    Unnest,
    Explode,
    Flatten,

    GenerateSeries,
    Sequence,
    Range,
    GenerateUuid,
    Uuid,
    GenRandomUuid,
    Newid,
    UuidGenerateV4,
    Md5,
    Md5Hash,
    Sha256,
    Sha2,
    Decode,
    Encode,

    RowNumber,
    Rownumber,
    Rank,
    Ranking,
    DenseRank,
    Denserank,
    Ntile,
    PercentRank,
    Percentrank,
    CumeDist,
    Cumedist,
    Lag,
    Lead,
    FirstValue,
    First,
    LastValue,
    Last,
    NthValue,

    Uniq,
    UniqExact,
    UniqHll12,
    UniqCombined,
    UniqCombined64,
    UniqThetaSketch,
    UniqArray,
    Quantile,
    QuantileExact,
    QuantileTDigest,
    QuantileTiming,
    QuantilesTDigest,
    QuantilesTiming,
    ArgMin,
    ArgMax,
    GroupArray,
    GroupArrayMovingAvg,
    GroupArrayMovingSum,
    Any,
    AnyLast,
    AnyHeavy,
    TopK,
    GroupUniqArray,
    SumWithOverflow,
    SumMap,
    MinMap,
    MaxMap,
    GroupBitmap,
    GroupBitmapAnd,
    GroupBitmapOr,
    GroupBitmapXor,
    RankCorr,
    ExponentialMovingAverage,
    IntervalLengthSum,
    Retention,
    WindowFunnel,

    Map,
    MapFromArrays,
    MapKeys,
    MapValues,
    MapContains,
    MapAdd,
    MapSubtract,
    MapUpdate,
    MapConcat,
    MapPopulateSeries,
    MapFilter,
    MapApply,
    MapExists,
    MapAll,
    MapSort,
    MapReverseSort,
    MapPartialSort,

    Custom(String),
}

impl FunctionName {
    pub fn parse(s: &str) -> Self {
        match s.to_uppercase().as_str() {
            "COUNT" => Self::Count,
            "SUM" => Self::Sum,
            "AVG" => Self::Avg,
            "AVERAGE" => Self::Average,
            "MIN" => Self::Min,
            "MINIMUM" => Self::Minimum,
            "MAX" => Self::Max,
            "MAXIMUM" => Self::Maximum,

            "STRING_AGG" => Self::StringAgg,
            "GROUP_CONCAT" => Self::GroupConcat,
            "LISTAGG" => Self::ListAgg,
            "ARRAY_AGG" => Self::ArrayAgg,
            "COLLECT" => Self::Collect,

            "STDDEV_POP" => Self::StddevPop,
            "STDDEVP" => Self::Stddevp,
            "STDDEV_SAMP" => Self::StddevSamp,
            "STDDEVS" => Self::Stddevs,
            "STDDEV" => Self::Stddev,
            "STDEV" => Self::Stdev,
            "STANDARD_DEVIATION" => Self::StandardDeviation,
            "VAR_POP" => Self::VarPop,
            "VARP" => Self::Varp,
            "VAR_SAMP" => Self::VarSamp,
            "VARS" => Self::Vars,
            "VARIANCE" => Self::Variance,
            "VAR" => Self::Var,
            "MEDIAN" => Self::Median,
            "PERCENTILE_CONT" => Self::PercentileCont,
            "PERCENTILE_DISC" => Self::PercentileDisc,
            "MODE" => Self::Mode,
            "CORR" => Self::Corr,
            "COVAR_POP" => Self::CovarPop,
            "COVAR_SAMP" => Self::CovarSamp,
            "COUNTIF" => Self::CountIf,

            "APPROX_COUNT_DISTINCT" => Self::ApproxCountDistinct,
            "APPROX_DISTINCT" => Self::ApproxDistinct,
            "APPROX_QUANTILES" => Self::ApproxQuantiles,
            "APPROX_TOP_COUNT" => Self::ApproxTopCount,
            "APPROX_TOP_SUM" => Self::ApproxTopSum,
            "NDV" => Self::Ndv,

            "UPPER" => Self::Upper,
            "UCASE" => Self::Ucase,
            "LOWER" => Self::Lower,
            "LCASE" => Self::Lcase,
            "TRIM" => Self::Trim,
            "BTRIM" => Self::Btrim,
            "LTRIM" => Self::Ltrim,
            "TRIMLEFT" => Self::TrimLeft,
            "RTRIM" => Self::Rtrim,
            "TRIMRIGHT" => Self::TrimRight,
            "CONCAT" => Self::Concat,
            "CONCATENATE" => Self::Concatenate,
            "SUBSTRING" => Self::Substring,
            "SUBSTR" => Self::Substr,
            "MID" => Self::Mid,
            "LENGTH" => Self::Length,
            "LEN" => Self::Len,
            "CHAR_LENGTH" => Self::CharLength,
            "CHARACTER_LENGTH" => Self::CharacterLength,
            "OCTET_LENGTH" => Self::OctetLength,
            "LENGTHB" => Self::Lengthb,
            "POSITION" => Self::Position,
            "STRPOS" => Self::Strpos,
            "INSTR" => Self::Instr,
            "LOCATE" => Self::Locate,
            "REPLACE" => Self::Replace,
            "STR_REPLACE" => Self::StrReplace,
            "SPLIT" => Self::Split,
            "SPLIT_PART" => Self::SplitPart,
            "STRING_SPLIT" => Self::StringSplit,
            "REVERSE" => Self::Reverse,
            "STRREV" => Self::Strrev,
            "REPEAT" => Self::Repeat,
            "REPLICATE" => Self::Replicate,
            "LEFT" => Self::Left,
            "RIGHT" => Self::Right,
            "LPAD" => Self::Lpad,
            "LEFTPAD" => Self::LeftPad,
            "RPAD" => Self::Rpad,
            "RIGHTPAD" => Self::RightPad,
            "ASCII" => Self::Ascii,
            "ORD" => Self::Ord,
            "CHR" => Self::Chr,
            "CHAR" => Self::Char,
            "INITCAP" => Self::Initcap,
            "PROPER" => Self::Proper,
            "TRANSLATE" => Self::Translate,

            "ABS" => Self::Abs,
            "ABSOLUTE" => Self::Absolute,
            "CEIL" => Self::Ceil,
            "CEILING" => Self::Ceiling,
            "FLOOR" => Self::Floor,
            "ROUND" => Self::Round,
            "RND" => Self::Rnd,
            "TRUNC" => Self::Trunc,
            "TRUNCATE" => Self::Truncate,
            "SQRT" => Self::Sqrt,
            "SQR" => Self::Sqr,
            "POW" => Self::Pow,
            "POWER" => Self::Power,
            "EXP" => Self::Exp,
            "EXPONENT" => Self::Exponent,
            "LN" => Self::Ln,
            "LOGE" => Self::Loge,
            "LOG" => Self::Log,
            "LOGARITHM" => Self::Logarithm,
            "LOG10" => Self::Log10,
            "LOG2" => Self::Log2,
            "SIGN" => Self::Sign,
            "SIGNUM" => Self::Signum,
            "MOD" => Self::Mod,
            "MODULO" => Self::Modulo,
            "DIV" => Self::Div,
            "INTDIV" => Self::Intdiv,
            "RANDOM" => Self::Random,
            "RAND" => Self::Rand,
            "PI" => Self::Pi,

            "SIN" => Self::Sin,
            "SINE" => Self::Sine,
            "COS" => Self::Cos,
            "COSINE" => Self::Cosine,
            "TAN" => Self::Tan,
            "TANGENT" => Self::Tangent,
            "ASIN" => Self::Asin,
            "ARCSINE" => Self::Arcsine,
            "ACOS" => Self::Acos,
            "ARCCOSINE" => Self::Arccosine,
            "ATAN" => Self::Atan,
            "ARCTANGENT" => Self::Arctangent,
            "ATAN2" => Self::Atan2,
            "ARCTANGENT2" => Self::Arctangent2,

            "CURRENT_DATE" => Self::CurrentDate,
            "CURDATE" => Self::Curdate,
            "TODAY" => Self::Today,
            "CURRENT_TIME" => Self::CurrentTime,
            "CURTIME" => Self::Curtime,
            "CURRENT_TIMESTAMP" => Self::CurrentTimestamp,
            "GETDATE" => Self::Getdate,
            "SYSDATE" => Self::Sysdate,
            "SYSTIMESTAMP" => Self::Systimestamp,
            "NOW" => Self::Now,
            "LOCALTIME" => Self::Localtime,
            "LOCALTIMESTAMP" => Self::Localtimestamp,
            "EXTRACT" => Self::Extract,
            "DATE_TRUNC" => Self::DateTrunc,
            "TRUNC_DATE" => Self::TruncDate,
            "DATE_PART" => Self::DatePart,
            "DATEPART" => Self::Datepart,
            "DATE_ADD" => Self::DateAdd,
            "DATEADD" => Self::Dateadd,
            "ADDDATE" => Self::Adddate,
            "DATE_SUB" => Self::DateSub,
            "DATESUB" => Self::Datesub,
            "SUBDATE" => Self::Subdate,
            "DATE_DIFF" => Self::DateDiff,
            "DATEDIFF" => Self::Datediff,
            "TIMESTAMPDIFF" => Self::Timestampdiff,
            "AGE" => Self::Age,
            "TO_TIMESTAMP" => Self::ToTimestamp,
            "STR_TO_DATE" => Self::StrToDate,
            "PARSE_DATETIME" => Self::ParseDatetime,
            "TIMESTAMP" => Self::Timestamp,
            "TO_DATE" => Self::ToDate,
            "DATE" => Self::Date,
            "CAST_DATE" => Self::CastDate,
            "FORMAT_TIMESTAMP" => Self::FormatTimestamp,
            "DATE_FORMAT" => Self::DateFormat,
            "TO_CHAR" => Self::ToChar,

            "COALESCE" => Self::Coalesce,
            "NULLIF" => Self::Nullif,
            "IFNULL" => Self::Ifnull,
            "NVL" => Self::Nvl,
            "ISNULL" => Self::Isnull,
            "IF" => Self::If,
            "IIF" => Self::Iif,
            "GREATEST" => Self::Greatest,
            "MAX_VALUE" => Self::MaxValue,
            "LEAST" => Self::Least,
            "MIN_VALUE" => Self::MinValue,

            "CAST" => Self::Cast,
            "TRY_CAST" => Self::TryCast,
            "TRYCAST" => Self::Trycast,
            "SAFE_CAST" => Self::SafeCast,
            "SAFECAST" => Self::Safecast,

            "JSON_EXTRACT" => Self::JsonExtract,
            "JSON_EXTRACT_SCALAR" => Self::JsonExtractScalar,
            "JSON_VALUE" => Self::JsonValue,
            "JSON_EXTRACT_STRING" => Self::JsonExtractString,
            "JSON_QUERY" => Self::JsonQuery,
            "JSON_ARRAY_LENGTH" => Self::JsonArrayLength,
            "JSON_LENGTH" => Self::JsonLength,
            "JSON_TYPEOF" => Self::JsonTypeof,
            "JSON_TYPE" => Self::JsonType,

            "ARRAY_LENGTH" => Self::ArrayLength,
            "CARDINALITY" => Self::Cardinality,
            "ARRAY_CONCAT" => Self::ArrayConcat,
            "ARRAY_CAT" => Self::ArrayCat,
            "ARRAY_CONTAINS" => Self::ArrayContains,
            "ARRAY_CONTAINS_ALL" => Self::ArrayContainsAll,
            "UNNEST" => Self::Unnest,
            "EXPLODE" => Self::Explode,
            "FLATTEN" => Self::Flatten,

            "GENERATE_SERIES" => Self::GenerateSeries,
            "SEQUENCE" => Self::Sequence,
            "RANGE" => Self::Range,
            "GENERATE_UUID" => Self::GenerateUuid,
            "UUID" => Self::Uuid,
            "GEN_RANDOM_UUID" => Self::GenRandomUuid,
            "NEWID" => Self::Newid,
            "UUID_GENERATE_V4" => Self::UuidGenerateV4,
            "MD5" => Self::Md5,
            "MD5_HASH" => Self::Md5Hash,
            "SHA256" => Self::Sha256,
            "SHA2" => Self::Sha2,
            "DECODE" => Self::Decode,
            "ENCODE" => Self::Encode,

            "ROW_NUMBER" => Self::RowNumber,
            "ROWNUMBER" => Self::Rownumber,
            "RANK" => Self::Rank,
            "RANKING" => Self::Ranking,
            "DENSE_RANK" => Self::DenseRank,
            "DENSERANK" => Self::Denserank,
            "NTILE" => Self::Ntile,
            "PERCENT_RANK" => Self::PercentRank,
            "PERCENTRANK" => Self::Percentrank,
            "CUME_DIST" => Self::CumeDist,
            "CUMEDIST" => Self::Cumedist,
            "LAG" => Self::Lag,
            "LEAD" => Self::Lead,
            "FIRST_VALUE" => Self::FirstValue,
            "FIRST" => Self::First,
            "LAST_VALUE" => Self::LastValue,
            "LAST" => Self::Last,
            "NTH_VALUE" => Self::NthValue,

            "UNIQ" => Self::Uniq,
            "UNIQ_EXACT" => Self::UniqExact,
            "UNIQEXACT" => Self::UniqExact,
            "UNIQ_HLL12" => Self::UniqHll12,
            "UNIQHLL12" => Self::UniqHll12,
            "UNIQ_COMBINED" => Self::UniqCombined,
            "UNIQCOMBINED" => Self::UniqCombined,
            "UNIQ_COMBINED_64" => Self::UniqCombined64,
            "UNIQCOMBINED64" => Self::UniqCombined64,
            "UNIQ_THETA_SKETCH" => Self::UniqThetaSketch,
            "UNIQTHETASKETCH" => Self::UniqThetaSketch,
            "UNIQ_ARRAY" => Self::UniqArray,
            "UNIQARRAY" => Self::UniqArray,
            "QUANTILE" => Self::Quantile,
            "QUANTILE_EXACT" => Self::QuantileExact,
            "QUANTILEEXACT" => Self::QuantileExact,
            "QUANTILE_TDIGEST" => Self::QuantileTDigest,
            "QUANTILETDIGEST" => Self::QuantileTDigest,
            "QUANTILE_TIMING" => Self::QuantileTiming,
            "QUANTILETIMING" => Self::QuantileTiming,
            "QUANTILES_TDIGEST" => Self::QuantilesTDigest,
            "QUANTILESTDIGEST" => Self::QuantilesTDigest,
            "QUANTILES_TIMING" => Self::QuantilesTiming,
            "QUANTILESTIMING" => Self::QuantilesTiming,
            "ARG_MIN" => Self::ArgMin,
            "ARGMIN" => Self::ArgMin,
            "ARG_MAX" => Self::ArgMax,
            "ARGMAX" => Self::ArgMax,
            "GROUP_ARRAY" => Self::GroupArray,
            "GROUPARRAY" => Self::GroupArray,
            "GROUP_ARRAY_MOVING_AVG" => Self::GroupArrayMovingAvg,
            "GROUPARRAYMOVINGAVG" => Self::GroupArrayMovingAvg,
            "GROUP_ARRAY_MOVING_SUM" => Self::GroupArrayMovingSum,
            "GROUPARRAYMOVINGSUM" => Self::GroupArrayMovingSum,
            "ANY" => Self::Any,
            "ANY_LAST" => Self::AnyLast,
            "ANYLAST" => Self::AnyLast,
            "ANY_HEAVY" => Self::AnyHeavy,
            "ANYHEAVY" => Self::AnyHeavy,
            "TOP_K" => Self::TopK,
            "TOPK" => Self::TopK,
            "GROUP_UNIQ_ARRAY" => Self::GroupUniqArray,
            "GROUPUNIQARRAY" => Self::GroupUniqArray,
            "SUM_WITH_OVERFLOW" => Self::SumWithOverflow,
            "SUMWITHOVERFLOW" => Self::SumWithOverflow,
            "SUM_MAP" => Self::SumMap,
            "SUMMAP" => Self::SumMap,
            "MIN_MAP" => Self::MinMap,
            "MINMAP" => Self::MinMap,
            "MAX_MAP" => Self::MaxMap,
            "MAXMAP" => Self::MaxMap,
            "GROUP_BITMAP" => Self::GroupBitmap,
            "GROUPBITMAP" => Self::GroupBitmap,
            "GROUP_BITMAP_AND" => Self::GroupBitmapAnd,
            "GROUPBITMAPAND" => Self::GroupBitmapAnd,
            "GROUP_BITMAP_OR" => Self::GroupBitmapOr,
            "GROUPBITMAPOR" => Self::GroupBitmapOr,
            "GROUP_BITMAP_XOR" => Self::GroupBitmapXor,
            "GROUPBITMAPXOR" => Self::GroupBitmapXor,
            "RANK_CORR" => Self::RankCorr,
            "RANKCORR" => Self::RankCorr,
            "EXPONENTIAL_MOVING_AVERAGE" => Self::ExponentialMovingAverage,
            "EXPONENTIALMOVINGAVERAGE" => Self::ExponentialMovingAverage,
            "INTERVAL_LENGTH_SUM" => Self::IntervalLengthSum,
            "INTERVALLENGTHSUM" => Self::IntervalLengthSum,
            "RETENTION" => Self::Retention,
            "WINDOW_FUNNEL" => Self::WindowFunnel,
            "WINDOWFUNNEL" => Self::WindowFunnel,

            "MAP" => Self::Map,
            "MAPFROMARRAYS" => Self::MapFromArrays,
            "MAPKEYS" | "MAP_KEYS" => Self::MapKeys,
            "MAPVALUES" | "MAP_VALUES" => Self::MapValues,
            "MAPCONTAINS" | "MAP_CONTAINS" => Self::MapContains,
            "MAPADD" | "MAP_ADD" => Self::MapAdd,
            "MAPSUBTRACT" | "MAP_SUBTRACT" => Self::MapSubtract,
            "MAPUPDATE" | "MAP_UPDATE" => Self::MapUpdate,
            "MAPCONCAT" | "MAP_CONCAT" => Self::MapConcat,
            "MAPPOPULATESERIES" | "MAP_POPULATE_SERIES" => Self::MapPopulateSeries,
            "MAPFILTER" | "MAP_FILTER" => Self::MapFilter,
            "MAPAPPLY" | "MAP_APPLY" => Self::MapApply,
            "MAPEXISTS" | "MAP_EXISTS" => Self::MapExists,
            "MAPALL" | "MAP_ALL" => Self::MapAll,
            "MAPSORT" | "MAP_SORT" => Self::MapSort,
            "MAPREVERSESORT" | "MAP_REVERSE_SORT" => Self::MapReverseSort,
            "MAPPARTIALSORT" | "MAP_PARTIAL_SORT" => Self::MapPartialSort,

            _ => Self::Custom(s.to_uppercase()),
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Count => "COUNT",
            Self::Sum => "SUM",
            Self::Avg => "AVG",
            Self::Average => "AVERAGE",
            Self::Min => "MIN",
            Self::Minimum => "MINIMUM",
            Self::Max => "MAX",
            Self::Maximum => "MAXIMUM",

            Self::StringAgg => "STRING_AGG",
            Self::GroupConcat => "GROUP_CONCAT",
            Self::ListAgg => "LISTAGG",
            Self::ArrayAgg => "ARRAY_AGG",
            Self::Collect => "COLLECT",

            Self::StddevPop => "STDDEV_POP",
            Self::Stddevp => "STDDEVP",
            Self::StddevSamp => "STDDEV_SAMP",
            Self::Stddevs => "STDDEVS",
            Self::Stddev => "STDDEV",
            Self::Stdev => "STDEV",
            Self::StandardDeviation => "STANDARD_DEVIATION",
            Self::VarPop => "VAR_POP",
            Self::Varp => "VARP",
            Self::VarSamp => "VAR_SAMP",
            Self::Vars => "VARS",
            Self::Variance => "VARIANCE",
            Self::Var => "VAR",
            Self::Median => "MEDIAN",
            Self::PercentileCont => "PERCENTILE_CONT",
            Self::PercentileDisc => "PERCENTILE_DISC",
            Self::Mode => "MODE",
            Self::Corr => "CORR",
            Self::CovarPop => "COVAR_POP",
            Self::CovarSamp => "COVAR_SAMP",
            Self::CountIf => "COUNTIF",

            Self::ApproxCountDistinct => "APPROX_COUNT_DISTINCT",
            Self::ApproxDistinct => "APPROX_DISTINCT",
            Self::ApproxQuantiles => "APPROX_QUANTILES",
            Self::ApproxTopCount => "APPROX_TOP_COUNT",
            Self::ApproxTopSum => "APPROX_TOP_SUM",
            Self::Ndv => "NDV",

            Self::Upper => "UPPER",
            Self::Ucase => "UCASE",
            Self::Lower => "LOWER",
            Self::Lcase => "LCASE",
            Self::Trim => "TRIM",
            Self::Btrim => "BTRIM",
            Self::Ltrim => "LTRIM",
            Self::TrimLeft => "TRIMLEFT",
            Self::Rtrim => "RTRIM",
            Self::TrimRight => "TRIMRIGHT",
            Self::Concat => "CONCAT",
            Self::Concatenate => "CONCATENATE",
            Self::Substring => "SUBSTRING",
            Self::Substr => "SUBSTR",
            Self::Mid => "MID",
            Self::Length => "LENGTH",
            Self::Len => "LEN",
            Self::CharLength => "CHAR_LENGTH",
            Self::CharacterLength => "CHARACTER_LENGTH",
            Self::OctetLength => "OCTET_LENGTH",
            Self::Lengthb => "LENGTHB",
            Self::Position => "POSITION",
            Self::Strpos => "STRPOS",
            Self::Instr => "INSTR",
            Self::Locate => "LOCATE",
            Self::Replace => "REPLACE",
            Self::StrReplace => "STR_REPLACE",
            Self::Split => "SPLIT",
            Self::SplitPart => "SPLIT_PART",
            Self::StringSplit => "STRING_SPLIT",
            Self::Reverse => "REVERSE",
            Self::Strrev => "STRREV",
            Self::Repeat => "REPEAT",
            Self::Replicate => "REPLICATE",
            Self::Left => "LEFT",
            Self::Right => "RIGHT",
            Self::Lpad => "LPAD",
            Self::LeftPad => "LEFTPAD",
            Self::Rpad => "RPAD",
            Self::RightPad => "RIGHTPAD",
            Self::Ascii => "ASCII",
            Self::Ord => "ORD",
            Self::Chr => "CHR",
            Self::Char => "CHAR",
            Self::Initcap => "INITCAP",
            Self::Proper => "PROPER",
            Self::Translate => "TRANSLATE",

            Self::Abs => "ABS",
            Self::Absolute => "ABSOLUTE",
            Self::Ceil => "CEIL",
            Self::Ceiling => "CEILING",
            Self::Floor => "FLOOR",
            Self::Round => "ROUND",
            Self::Rnd => "RND",
            Self::Trunc => "TRUNC",
            Self::Truncate => "TRUNCATE",
            Self::Sqrt => "SQRT",
            Self::Sqr => "SQR",
            Self::Pow => "POW",
            Self::Power => "POWER",
            Self::Exp => "EXP",
            Self::Exponent => "EXPONENT",
            Self::Ln => "LN",
            Self::Loge => "LOGE",
            Self::Log => "LOG",
            Self::Logarithm => "LOGARITHM",
            Self::Log10 => "LOG10",
            Self::Log2 => "LOG2",
            Self::Sign => "SIGN",
            Self::Signum => "SIGNUM",
            Self::Mod => "MOD",
            Self::Modulo => "MODULO",
            Self::Div => "DIV",
            Self::Intdiv => "INTDIV",
            Self::Random => "RANDOM",
            Self::Rand => "RAND",
            Self::Pi => "PI",

            Self::Sin => "SIN",
            Self::Sine => "SINE",
            Self::Cos => "COS",
            Self::Cosine => "COSINE",
            Self::Tan => "TAN",
            Self::Tangent => "TANGENT",
            Self::Asin => "ASIN",
            Self::Arcsine => "ARCSINE",
            Self::Acos => "ACOS",
            Self::Arccosine => "ARCCOSINE",
            Self::Atan => "ATAN",
            Self::Arctangent => "ARCTANGENT",
            Self::Atan2 => "ATAN2",
            Self::Arctangent2 => "ARCTANGENT2",

            Self::CurrentDate => "CURRENT_DATE",
            Self::Curdate => "CURDATE",
            Self::Today => "TODAY",
            Self::CurrentTime => "CURRENT_TIME",
            Self::Curtime => "CURTIME",
            Self::CurrentTimestamp => "CURRENT_TIMESTAMP",
            Self::Getdate => "GETDATE",
            Self::Sysdate => "SYSDATE",
            Self::Systimestamp => "SYSTIMESTAMP",
            Self::Now => "NOW",
            Self::Localtime => "LOCALTIME",
            Self::Localtimestamp => "LOCALTIMESTAMP",
            Self::Extract => "EXTRACT",
            Self::DateTrunc => "DATE_TRUNC",
            Self::TruncDate => "TRUNC_DATE",
            Self::DatePart => "DATE_PART",
            Self::Datepart => "DATEPART",
            Self::DateAdd => "DATE_ADD",
            Self::Dateadd => "DATEADD",
            Self::Adddate => "ADDDATE",
            Self::DateSub => "DATE_SUB",
            Self::Datesub => "DATESUB",
            Self::Subdate => "SUBDATE",
            Self::DateDiff => "DATE_DIFF",
            Self::Datediff => "DATEDIFF",
            Self::Timestampdiff => "TIMESTAMPDIFF",
            Self::Age => "AGE",
            Self::ToTimestamp => "TO_TIMESTAMP",
            Self::StrToDate => "STR_TO_DATE",
            Self::ParseDatetime => "PARSE_DATETIME",
            Self::Timestamp => "TIMESTAMP",
            Self::ToDate => "TO_DATE",
            Self::Date => "DATE",
            Self::CastDate => "CAST_DATE",
            Self::FormatTimestamp => "FORMAT_TIMESTAMP",
            Self::DateFormat => "DATE_FORMAT",
            Self::ToChar => "TO_CHAR",

            Self::Coalesce => "COALESCE",
            Self::Nullif => "NULLIF",
            Self::Ifnull => "IFNULL",
            Self::Nvl => "NVL",
            Self::Isnull => "ISNULL",
            Self::If => "IF",
            Self::Iif => "IIF",
            Self::Greatest => "GREATEST",
            Self::MaxValue => "MAX_VALUE",
            Self::Least => "LEAST",
            Self::MinValue => "MIN_VALUE",

            Self::Cast => "CAST",
            Self::TryCast => "TRY_CAST",
            Self::Trycast => "TRYCAST",
            Self::SafeCast => "SAFE_CAST",
            Self::Safecast => "SAFECAST",

            Self::JsonExtract => "JSON_EXTRACT",
            Self::JsonExtractScalar => "JSON_EXTRACT_SCALAR",
            Self::JsonValue => "JSON_VALUE",
            Self::JsonExtractString => "JSON_EXTRACT_STRING",
            Self::JsonQuery => "JSON_QUERY",
            Self::JsonArrayLength => "JSON_ARRAY_LENGTH",
            Self::JsonLength => "JSON_LENGTH",
            Self::JsonTypeof => "JSON_TYPEOF",
            Self::JsonType => "JSON_TYPE",

            Self::ArrayLength => "ARRAY_LENGTH",
            Self::Cardinality => "CARDINALITY",
            Self::ArrayConcat => "ARRAY_CONCAT",
            Self::ArrayCat => "ARRAY_CAT",
            Self::ArrayContains => "ARRAY_CONTAINS",
            Self::ArrayContainsAll => "ARRAY_CONTAINS_ALL",
            Self::Unnest => "UNNEST",
            Self::Explode => "EXPLODE",
            Self::Flatten => "FLATTEN",

            Self::GenerateSeries => "GENERATE_SERIES",
            Self::Sequence => "SEQUENCE",
            Self::Range => "RANGE",
            Self::GenerateUuid => "GENERATE_UUID",
            Self::Uuid => "UUID",
            Self::GenRandomUuid => "GEN_RANDOM_UUID",
            Self::Newid => "NEWID",
            Self::UuidGenerateV4 => "UUID_GENERATE_V4",
            Self::Md5 => "MD5",
            Self::Md5Hash => "MD5_HASH",
            Self::Sha256 => "SHA256",
            Self::Sha2 => "SHA2",
            Self::Decode => "DECODE",
            Self::Encode => "ENCODE",

            Self::RowNumber => "ROW_NUMBER",
            Self::Rownumber => "ROWNUMBER",
            Self::Rank => "RANK",
            Self::Ranking => "RANKING",
            Self::DenseRank => "DENSE_RANK",
            Self::Denserank => "DENSERANK",
            Self::Ntile => "NTILE",
            Self::PercentRank => "PERCENT_RANK",
            Self::Percentrank => "PERCENTRANK",
            Self::CumeDist => "CUME_DIST",
            Self::Cumedist => "CUMEDIST",
            Self::Lag => "LAG",
            Self::Lead => "LEAD",
            Self::FirstValue => "FIRST_VALUE",
            Self::First => "FIRST",
            Self::LastValue => "LAST_VALUE",
            Self::Last => "LAST",
            Self::NthValue => "NTH_VALUE",

            Self::Uniq => "UNIQ",
            Self::UniqExact => "UNIQ_EXACT",
            Self::UniqHll12 => "UNIQ_HLL12",
            Self::UniqCombined => "UNIQ_COMBINED",
            Self::UniqCombined64 => "UNIQ_COMBINED_64",
            Self::UniqThetaSketch => "UNIQ_THETA_SKETCH",
            Self::UniqArray => "UNIQ_ARRAY",
            Self::Quantile => "QUANTILE",
            Self::QuantileExact => "QUANTILE_EXACT",
            Self::QuantileTDigest => "QUANTILE_TDIGEST",
            Self::QuantileTiming => "QUANTILE_TIMING",
            Self::QuantilesTDigest => "QUANTILES_TDIGEST",
            Self::QuantilesTiming => "QUANTILES_TIMING",
            Self::ArgMin => "ARG_MIN",
            Self::ArgMax => "ARG_MAX",
            Self::GroupArray => "GROUP_ARRAY",
            Self::GroupArrayMovingAvg => "GROUP_ARRAY_MOVING_AVG",
            Self::GroupArrayMovingSum => "GROUP_ARRAY_MOVING_SUM",
            Self::Any => "ANY",
            Self::AnyLast => "ANY_LAST",
            Self::AnyHeavy => "ANY_HEAVY",
            Self::TopK => "TOP_K",
            Self::GroupUniqArray => "GROUP_UNIQ_ARRAY",
            Self::SumWithOverflow => "SUM_WITH_OVERFLOW",
            Self::SumMap => "SUM_MAP",
            Self::MinMap => "MIN_MAP",
            Self::MaxMap => "MAX_MAP",
            Self::GroupBitmap => "GROUP_BITMAP",
            Self::GroupBitmapAnd => "GROUP_BITMAP_AND",
            Self::GroupBitmapOr => "GROUP_BITMAP_OR",
            Self::GroupBitmapXor => "GROUP_BITMAP_XOR",
            Self::RankCorr => "RANK_CORR",
            Self::ExponentialMovingAverage => "EXPONENTIAL_MOVING_AVERAGE",
            Self::IntervalLengthSum => "INTERVAL_LENGTH_SUM",
            Self::Retention => "RETENTION",
            Self::WindowFunnel => "WINDOW_FUNNEL",

            Self::Map => "MAP",
            Self::MapFromArrays => "MAPFROMARRAYS",
            Self::MapKeys => "MAPKEYS",
            Self::MapValues => "MAPVALUES",
            Self::MapContains => "MAPCONTAINS",
            Self::MapAdd => "MAPADD",
            Self::MapSubtract => "MAPSUBTRACT",
            Self::MapUpdate => "MAPUPDATE",
            Self::MapConcat => "MAPCONCAT",
            Self::MapPopulateSeries => "MAPPOPULATESERIES",
            Self::MapFilter => "MAPFILTER",
            Self::MapApply => "MAPAPPLY",
            Self::MapExists => "MAPEXISTS",
            Self::MapAll => "MAPALL",
            Self::MapSort => "MAPSORT",
            Self::MapReverseSort => "MAPREVERSESORT",
            Self::MapPartialSort => "MAPPARTIALSORT",

            Self::Custom(name) => name,
        }
    }

    pub fn is_aggregate(&self) -> bool {
        matches!(
            self,
            Self::Count
                | Self::Sum
                | Self::Avg
                | Self::Average
                | Self::Min
                | Self::Minimum
                | Self::Max
                | Self::Maximum
                | Self::StringAgg
                | Self::GroupConcat
                | Self::ListAgg
                | Self::ArrayAgg
                | Self::Collect
                | Self::StddevPop
                | Self::Stddevp
                | Self::StddevSamp
                | Self::Stddevs
                | Self::Stddev
                | Self::Stdev
                | Self::StandardDeviation
                | Self::VarPop
                | Self::Varp
                | Self::VarSamp
                | Self::Vars
                | Self::Variance
                | Self::Var
                | Self::Median
                | Self::PercentileCont
                | Self::PercentileDisc
                | Self::Mode
                | Self::Corr
                | Self::CovarPop
                | Self::CovarSamp
                | Self::CountIf
                | Self::ApproxCountDistinct
                | Self::ApproxDistinct
                | Self::ApproxQuantiles
                | Self::ApproxTopCount
                | Self::ApproxTopSum
                | Self::Ndv
                | Self::Uniq
                | Self::UniqExact
                | Self::UniqHll12
                | Self::UniqCombined
                | Self::UniqCombined64
                | Self::UniqThetaSketch
                | Self::UniqArray
                | Self::Quantile
                | Self::QuantileExact
                | Self::QuantileTDigest
                | Self::QuantileTiming
                | Self::QuantilesTDigest
                | Self::QuantilesTiming
                | Self::ArgMin
                | Self::ArgMax
                | Self::GroupArray
                | Self::GroupArrayMovingAvg
                | Self::GroupArrayMovingSum
                | Self::Any
                | Self::AnyLast
                | Self::AnyHeavy
                | Self::TopK
                | Self::GroupUniqArray
                | Self::SumWithOverflow
                | Self::SumMap
                | Self::MinMap
                | Self::MaxMap
                | Self::GroupBitmap
                | Self::GroupBitmapAnd
                | Self::GroupBitmapOr
                | Self::GroupBitmapXor
                | Self::RankCorr
                | Self::ExponentialMovingAverage
                | Self::IntervalLengthSum
                | Self::Retention
                | Self::WindowFunnel
        )
    }

    pub fn is_window(&self) -> bool {
        matches!(
            self,
            Self::RowNumber
                | Self::Rownumber
                | Self::Rank
                | Self::Ranking
                | Self::DenseRank
                | Self::Denserank
                | Self::Ntile
                | Self::PercentRank
                | Self::Percentrank
                | Self::CumeDist
                | Self::Cumedist
                | Self::Lag
                | Self::Lead
                | Self::FirstValue
                | Self::First
                | Self::LastValue
                | Self::Last
                | Self::NthValue
        )
    }

    pub fn is_scalar(&self) -> bool {
        !self.is_aggregate() && !self.is_window()
    }
}

impl std::fmt::Display for FunctionName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl From<&str> for FunctionName {
    fn from(s: &str) -> Self {
        Self::parse(s)
    }
}

impl From<String> for FunctionName {
    fn from(s: String) -> Self {
        Self::parse(&s)
    }
}
