#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum FunctionName {
    Count,
    Sum,
    Avg,
    Min,
    Max,
    AnyValue,

    StringAgg,
    ArrayAgg,
    CountIf,

    StddevPop,
    StddevSamp,
    Stddev,
    VarPop,
    VarSamp,
    Variance,
    Corr,
    CovarPop,
    CovarSamp,

    LogicalAnd,
    LogicalOr,
    BitAnd,
    BitOr,
    BitXor,

    ApproxCountDistinct,
    ApproxQuantiles,
    ApproxTopCount,
    ApproxTopSum,

    HllCountInit,
    HllCountMerge,
    HllCountMergePartial,
    HllCountExtract,

    RowNumber,
    Rank,
    DenseRank,
    Ntile,
    PercentRank,
    CumeDist,
    Lag,
    Lead,
    FirstValue,
    LastValue,
    NthValue,
    PercentileCont,
    PercentileDisc,

    Upper,
    Lower,
    Trim,
    Ltrim,
    Rtrim,
    Concat,
    Substr,
    Substring,
    Length,
    CharLength,
    CharacterLength,
    OctetLength,
    ByteLength,
    Position,
    Strpos,
    Instr,
    Replace,
    Split,
    Reverse,
    Repeat,
    Left,
    Right,
    Lpad,
    Rpad,
    Ascii,
    Chr,
    Initcap,
    Translate,
    Format,
    Normalize,
    NormalizeAndCasefold,
    RegexpContains,
    RegexpReplace,
    RegexpExtract,
    RegexpExtractAll,
    RegexpInstr,
    RegexpSubstr,
    StartsWith,
    EndsWith,
    ContainsSubstr,
    SafeConvertBytesToString,
    CodePointsToBytes,
    CodePointsToString,
    ToCodePoints,
    ToBase32,
    ToBase64,
    ToHex,
    Soundex,
    Unicode,

    Abs,
    Ceil,
    Ceiling,
    Floor,
    Round,
    Trunc,
    Sqrt,
    Pow,
    Power,
    Exp,
    Ln,
    Log,
    Log10,
    Sign,
    Mod,
    Div,
    Rand,
    Pi,
    Greatest,
    Least,
    IsInf,
    IsNan,
    IeeeDivide,
    SafeDivide,
    SafeMultiply,
    SafeAdd,
    SafeSubtract,
    SafeNegate,
    RangeBucket,

    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    Sinh,
    Cosh,
    Tanh,
    Asinh,
    Acosh,
    Atanh,
    Cot,
    Coth,
    Sec,
    Sech,
    Csc,
    Csch,
    Cbrt,

    CurrentDate,
    CurrentDatetime,
    CurrentTime,
    CurrentTimestamp,
    Extract,

    Date,
    DateAdd,
    DateDiff,
    DateSub,
    DateTrunc,
    DateFromUnixDate,

    Datetime,
    DatetimeAdd,
    DatetimeDiff,
    DatetimeSub,
    DatetimeTrunc,

    Time,
    TimeAdd,
    TimeDiff,
    TimeSub,
    TimeTrunc,

    Timestamp,
    TimestampAdd,
    TimestampDiff,
    TimestampSub,
    TimestampTrunc,
    TimestampMicros,
    TimestampMillis,
    TimestampSeconds,

    UnixDate,
    UnixMicros,
    UnixMillis,
    UnixSeconds,

    FormatDate,
    FormatDatetime,
    FormatTime,
    FormatTimestamp,

    ParseDate,
    ParseDatetime,
    ParseTime,
    ParseTimestamp,

    MakeDate,
    MakeInterval,
    MakeTime,
    MakeTimestamp,
    LastDay,

    IntervalParse,

    Coalesce,
    Nullif,
    Ifnull,
    If,

    Cast,
    SafeCast,

    JsonExtract,
    JsonExtractScalar,
    JsonValue,
    JsonQuery,
    JsonType,
    JsonExtractArray,
    JsonExtractStringArray,
    JsonQueryArray,
    JsonValueArray,
    ParseJson,
    ToJson,
    ToJsonString,
    LaxBool,
    LaxInt64,
    LaxFloat64,
    LaxString,
    JsonBool,
    JsonInt64,
    JsonFloat64,
    JsonString,

    ArrayLength,
    ArrayConcat,
    ArrayReverse,
    ArrayToString,
    GenerateArray,
    GenerateDateArray,
    GenerateTimestampArray,
    ArrayFilter,
    ArrayTransform,
    ArrayIncludes,
    ArrayIncludesAny,
    ArrayIncludesAll,
    Offset,
    Ordinal,
    SafeOffset,
    SafeOrdinal,
    Unnest,

    GenerateUuid,
    Md5,
    Sha1,
    Sha256,
    Sha512,
    FarmFingerprint,
    FromHex,
    FromBase64,

    StGeogpoint,
    StGeogfromtext,
    StGeogfromgeojson,
    StAstext,
    StAsgeojson,
    StAsbinary,
    StX,
    StY,
    StGeometrytype,
    StIsempty,
    StIsclosed,
    StIscollection,
    StDimension,
    StNumpoints,
    StNpoints,
    StPointn,
    StStartpoint,
    StEndpoint,
    StMakeline,
    StMakepolygon,
    StDistance,
    StLength,
    StArea,
    StPerimeter,
    StMaxdistance,
    StAzimuth,
    StCentroid,
    StContains,
    StCovers,
    StCoveredby,
    StDisjoint,
    StDwithin,
    StEquals,
    StIntersects,
    StTouches,
    StWithin,
    StBoundary,
    StBuffer,
    StBufferwithtolerance,
    StClosestpoint,
    StConvexhull,
    StDifference,
    StIntersection,
    StSimplify,
    StSnaptogrid,
    StUnion,
    StBoundingbox,
    StGeohash,
    StGeogpointfromgeohash,

    NetIpFromString,
    NetSafeIpFromString,
    NetIpv4FromInt64,
    NetIpNetMask,
    NetIpTrunc,
    NetIpv4ToInt64,
    NetIpToString,
    NetHost,
    NetPublicSuffix,
    NetRegDomain,
    NetIpInNet,
    NetMakeNet,
    NetIpIsPrivate,

    KeysKeysetChain,
    AeadEncrypt,
    DeterministicEncrypt,
    AeadDecryptBytes,
    DeterministicDecryptBytes,
    AeadDecryptString,
    DeterministicDecryptString,

    Error,
    SessionUser,
    CurrentUser,
    Array,
    Struct,

    Custom(String),
}

impl FunctionName {
    pub fn parse(s: &str) -> Self {
        match s.to_uppercase().as_str() {
            "COUNT" => Self::Count,
            "SUM" => Self::Sum,
            "AVG" => Self::Avg,
            "MIN" => Self::Min,
            "MAX" => Self::Max,
            "ANY_VALUE" => Self::AnyValue,

            "STRING_AGG" => Self::StringAgg,
            "ARRAY_AGG" => Self::ArrayAgg,
            "COUNTIF" => Self::CountIf,

            "STDDEV_POP" => Self::StddevPop,
            "STDDEV_SAMP" => Self::StddevSamp,
            "STDDEV" => Self::Stddev,
            "VAR_POP" => Self::VarPop,
            "VAR_SAMP" => Self::VarSamp,
            "VARIANCE" => Self::Variance,
            "CORR" => Self::Corr,
            "COVAR_POP" => Self::CovarPop,
            "COVAR_SAMP" => Self::CovarSamp,

            "LOGICAL_AND" => Self::LogicalAnd,
            "LOGICAL_OR" => Self::LogicalOr,
            "BIT_AND" => Self::BitAnd,
            "BIT_OR" => Self::BitOr,
            "BIT_XOR" => Self::BitXor,

            "APPROX_COUNT_DISTINCT" => Self::ApproxCountDistinct,
            "APPROX_QUANTILES" => Self::ApproxQuantiles,
            "APPROX_TOP_COUNT" => Self::ApproxTopCount,
            "APPROX_TOP_SUM" => Self::ApproxTopSum,

            "HLL_COUNT.INIT" | "HLL_COUNT_INIT" => Self::HllCountInit,
            "HLL_COUNT.MERGE" | "HLL_COUNT_MERGE" => Self::HllCountMerge,
            "HLL_COUNT.MERGE_PARTIAL" | "HLL_COUNT_MERGE_PARTIAL" => Self::HllCountMergePartial,
            "HLL_COUNT.EXTRACT" | "HLL_COUNT_EXTRACT" => Self::HllCountExtract,

            "ROW_NUMBER" => Self::RowNumber,
            "RANK" => Self::Rank,
            "DENSE_RANK" => Self::DenseRank,
            "NTILE" => Self::Ntile,
            "PERCENT_RANK" => Self::PercentRank,
            "CUME_DIST" => Self::CumeDist,
            "LAG" => Self::Lag,
            "LEAD" => Self::Lead,
            "FIRST_VALUE" => Self::FirstValue,
            "LAST_VALUE" => Self::LastValue,
            "NTH_VALUE" => Self::NthValue,
            "PERCENTILE_CONT" => Self::PercentileCont,
            "PERCENTILE_DISC" => Self::PercentileDisc,

            "UPPER" => Self::Upper,
            "LOWER" => Self::Lower,
            "TRIM" => Self::Trim,
            "LTRIM" => Self::Ltrim,
            "RTRIM" => Self::Rtrim,
            "CONCAT" => Self::Concat,
            "SUBSTR" => Self::Substr,
            "SUBSTRING" => Self::Substring,
            "LENGTH" => Self::Length,
            "CHAR_LENGTH" => Self::CharLength,
            "CHARACTER_LENGTH" => Self::CharacterLength,
            "OCTET_LENGTH" => Self::OctetLength,
            "BYTE_LENGTH" => Self::ByteLength,
            "POSITION" => Self::Position,
            "STRPOS" => Self::Strpos,
            "INSTR" => Self::Instr,
            "REPLACE" => Self::Replace,
            "SPLIT" => Self::Split,
            "REVERSE" => Self::Reverse,
            "REPEAT" => Self::Repeat,
            "LEFT" => Self::Left,
            "RIGHT" => Self::Right,
            "LPAD" => Self::Lpad,
            "RPAD" => Self::Rpad,
            "ASCII" => Self::Ascii,
            "CHR" => Self::Chr,
            "INITCAP" => Self::Initcap,
            "TRANSLATE" => Self::Translate,
            "FORMAT" => Self::Format,
            "NORMALIZE" => Self::Normalize,
            "NORMALIZE_AND_CASEFOLD" => Self::NormalizeAndCasefold,
            "REGEXP_CONTAINS" => Self::RegexpContains,
            "REGEXP_REPLACE" => Self::RegexpReplace,
            "REGEXP_EXTRACT" => Self::RegexpExtract,
            "REGEXP_EXTRACT_ALL" => Self::RegexpExtractAll,
            "REGEXP_INSTR" => Self::RegexpInstr,
            "REGEXP_SUBSTR" => Self::RegexpSubstr,
            "STARTS_WITH" => Self::StartsWith,
            "ENDS_WITH" => Self::EndsWith,
            "CONTAINS_SUBSTR" => Self::ContainsSubstr,
            "SAFE_CONVERT_BYTES_TO_STRING" => Self::SafeConvertBytesToString,
            "CODE_POINTS_TO_BYTES" => Self::CodePointsToBytes,
            "CODE_POINTS_TO_STRING" => Self::CodePointsToString,
            "TO_CODE_POINTS" => Self::ToCodePoints,
            "TO_BASE32" => Self::ToBase32,
            "TO_BASE64" => Self::ToBase64,
            "TO_HEX" => Self::ToHex,
            "SOUNDEX" => Self::Soundex,
            "UNICODE" => Self::Unicode,

            "ABS" => Self::Abs,
            "CEIL" => Self::Ceil,
            "CEILING" => Self::Ceiling,
            "FLOOR" => Self::Floor,
            "ROUND" => Self::Round,
            "TRUNC" => Self::Trunc,
            "SQRT" => Self::Sqrt,
            "POW" => Self::Pow,
            "POWER" => Self::Power,
            "EXP" => Self::Exp,
            "LN" => Self::Ln,
            "LOG" => Self::Log,
            "LOG10" => Self::Log10,
            "SIGN" => Self::Sign,
            "MOD" => Self::Mod,
            "DIV" => Self::Div,
            "RAND" => Self::Rand,
            "PI" => Self::Pi,
            "GREATEST" => Self::Greatest,
            "LEAST" => Self::Least,
            "IS_INF" => Self::IsInf,
            "IS_NAN" => Self::IsNan,
            "IEEE_DIVIDE" => Self::IeeeDivide,
            "SAFE_DIVIDE" => Self::SafeDivide,
            "SAFE_MULTIPLY" => Self::SafeMultiply,
            "SAFE_ADD" => Self::SafeAdd,
            "SAFE_SUBTRACT" => Self::SafeSubtract,
            "SAFE_NEGATE" => Self::SafeNegate,
            "RANGE_BUCKET" => Self::RangeBucket,

            "SIN" => Self::Sin,
            "COS" => Self::Cos,
            "TAN" => Self::Tan,
            "ASIN" => Self::Asin,
            "ACOS" => Self::Acos,
            "ATAN" => Self::Atan,
            "ATAN2" => Self::Atan2,
            "SINH" => Self::Sinh,
            "COSH" => Self::Cosh,
            "TANH" => Self::Tanh,
            "ASINH" => Self::Asinh,
            "ACOSH" => Self::Acosh,
            "ATANH" => Self::Atanh,
            "COT" => Self::Cot,
            "COTH" => Self::Coth,
            "SEC" => Self::Sec,
            "SECH" => Self::Sech,
            "CSC" => Self::Csc,
            "CSCH" => Self::Csch,
            "CBRT" => Self::Cbrt,

            "CURRENT_DATE" => Self::CurrentDate,
            "CURRENT_DATETIME" => Self::CurrentDatetime,
            "CURRENT_TIME" => Self::CurrentTime,
            "CURRENT_TIMESTAMP" => Self::CurrentTimestamp,
            "EXTRACT" => Self::Extract,

            "DATE" => Self::Date,
            "DATE_ADD" => Self::DateAdd,
            "DATE_DIFF" => Self::DateDiff,
            "DATE_SUB" => Self::DateSub,
            "DATE_TRUNC" => Self::DateTrunc,
            "DATE_FROM_UNIX_DATE" => Self::DateFromUnixDate,

            "DATETIME" => Self::Datetime,
            "DATETIME_ADD" => Self::DatetimeAdd,
            "DATETIME_DIFF" => Self::DatetimeDiff,
            "DATETIME_SUB" => Self::DatetimeSub,
            "DATETIME_TRUNC" => Self::DatetimeTrunc,

            "TIME" => Self::Time,
            "TIME_ADD" => Self::TimeAdd,
            "TIME_DIFF" => Self::TimeDiff,
            "TIME_SUB" => Self::TimeSub,
            "TIME_TRUNC" => Self::TimeTrunc,

            "TIMESTAMP" => Self::Timestamp,
            "TIMESTAMP_ADD" => Self::TimestampAdd,
            "TIMESTAMP_DIFF" => Self::TimestampDiff,
            "TIMESTAMP_SUB" => Self::TimestampSub,
            "TIMESTAMP_TRUNC" => Self::TimestampTrunc,
            "TIMESTAMP_MICROS" => Self::TimestampMicros,
            "TIMESTAMP_MILLIS" => Self::TimestampMillis,
            "TIMESTAMP_SECONDS" => Self::TimestampSeconds,

            "UNIX_DATE" => Self::UnixDate,
            "UNIX_MICROS" => Self::UnixMicros,
            "UNIX_MILLIS" => Self::UnixMillis,
            "UNIX_SECONDS" => Self::UnixSeconds,

            "FORMAT_DATE" => Self::FormatDate,
            "FORMAT_DATETIME" => Self::FormatDatetime,
            "FORMAT_TIME" => Self::FormatTime,
            "FORMAT_TIMESTAMP" => Self::FormatTimestamp,

            "PARSE_DATE" => Self::ParseDate,
            "PARSE_DATETIME" => Self::ParseDatetime,
            "PARSE_TIME" => Self::ParseTime,
            "PARSE_TIMESTAMP" => Self::ParseTimestamp,

            "MAKE_DATE" => Self::MakeDate,
            "MAKE_INTERVAL" => Self::MakeInterval,
            "MAKE_TIME" => Self::MakeTime,
            "MAKE_TIMESTAMP" => Self::MakeTimestamp,
            "LAST_DAY" => Self::LastDay,

            "INTERVAL_PARSE" => Self::IntervalParse,

            "COALESCE" => Self::Coalesce,
            "NULLIF" => Self::Nullif,
            "IFNULL" => Self::Ifnull,
            "IF" => Self::If,

            "CAST" => Self::Cast,
            "SAFE_CAST" => Self::SafeCast,

            "JSON_EXTRACT" => Self::JsonExtract,
            "JSON_EXTRACT_SCALAR" => Self::JsonExtractScalar,
            "JSON_VALUE" => Self::JsonValue,
            "JSON_QUERY" => Self::JsonQuery,
            "JSON_TYPE" => Self::JsonType,
            "JSON_EXTRACT_ARRAY" => Self::JsonExtractArray,
            "JSON_EXTRACT_STRING_ARRAY" => Self::JsonExtractStringArray,
            "JSON_QUERY_ARRAY" => Self::JsonQueryArray,
            "JSON_VALUE_ARRAY" => Self::JsonValueArray,
            "PARSE_JSON" => Self::ParseJson,
            "TO_JSON" => Self::ToJson,
            "TO_JSON_STRING" => Self::ToJsonString,
            "LAX_BOOL" => Self::LaxBool,
            "LAX_INT64" => Self::LaxInt64,
            "LAX_FLOAT64" => Self::LaxFloat64,
            "LAX_STRING" => Self::LaxString,
            "BOOL" => Self::JsonBool,
            "INT64" => Self::JsonInt64,
            "FLOAT64" => Self::JsonFloat64,
            "STRING" => Self::JsonString,

            "ARRAY_LENGTH" => Self::ArrayLength,
            "ARRAY_CONCAT" => Self::ArrayConcat,
            "ARRAY_REVERSE" => Self::ArrayReverse,
            "ARRAY_TO_STRING" => Self::ArrayToString,
            "GENERATE_ARRAY" => Self::GenerateArray,
            "GENERATE_DATE_ARRAY" => Self::GenerateDateArray,
            "GENERATE_TIMESTAMP_ARRAY" => Self::GenerateTimestampArray,
            "ARRAY_FILTER" => Self::ArrayFilter,
            "ARRAY_TRANSFORM" => Self::ArrayTransform,
            "ARRAY_INCLUDES" => Self::ArrayIncludes,
            "ARRAY_INCLUDES_ANY" => Self::ArrayIncludesAny,
            "ARRAY_INCLUDES_ALL" => Self::ArrayIncludesAll,
            "OFFSET" => Self::Offset,
            "ORDINAL" => Self::Ordinal,
            "SAFE_OFFSET" => Self::SafeOffset,
            "SAFE_ORDINAL" => Self::SafeOrdinal,
            "UNNEST" => Self::Unnest,

            "GENERATE_UUID" => Self::GenerateUuid,
            "MD5" => Self::Md5,
            "SHA1" => Self::Sha1,
            "SHA256" => Self::Sha256,
            "SHA512" => Self::Sha512,
            "FARM_FINGERPRINT" => Self::FarmFingerprint,
            "FROM_HEX" => Self::FromHex,
            "FROM_BASE64" => Self::FromBase64,

            "ST_GEOGPOINT" => Self::StGeogpoint,
            "ST_GEOGFROMTEXT" => Self::StGeogfromtext,
            "ST_GEOGFROMGEOJSON" => Self::StGeogfromgeojson,
            "ST_ASTEXT" => Self::StAstext,
            "ST_ASGEOJSON" => Self::StAsgeojson,
            "ST_ASBINARY" => Self::StAsbinary,
            "ST_X" => Self::StX,
            "ST_Y" => Self::StY,
            "ST_GEOMETRYTYPE" => Self::StGeometrytype,
            "ST_ISEMPTY" => Self::StIsempty,
            "ST_ISCLOSED" => Self::StIsclosed,
            "ST_ISCOLLECTION" => Self::StIscollection,
            "ST_DIMENSION" => Self::StDimension,
            "ST_NUMPOINTS" => Self::StNumpoints,
            "ST_NPOINTS" => Self::StNpoints,
            "ST_POINTN" => Self::StPointn,
            "ST_STARTPOINT" => Self::StStartpoint,
            "ST_ENDPOINT" => Self::StEndpoint,
            "ST_MAKELINE" => Self::StMakeline,
            "ST_MAKEPOLYGON" => Self::StMakepolygon,
            "ST_DISTANCE" => Self::StDistance,
            "ST_LENGTH" => Self::StLength,
            "ST_AREA" => Self::StArea,
            "ST_PERIMETER" => Self::StPerimeter,
            "ST_MAXDISTANCE" => Self::StMaxdistance,
            "ST_AZIMUTH" => Self::StAzimuth,
            "ST_CENTROID" => Self::StCentroid,
            "ST_CONTAINS" => Self::StContains,
            "ST_COVERS" => Self::StCovers,
            "ST_COVEREDBY" => Self::StCoveredby,
            "ST_DISJOINT" => Self::StDisjoint,
            "ST_DWITHIN" => Self::StDwithin,
            "ST_EQUALS" => Self::StEquals,
            "ST_INTERSECTS" => Self::StIntersects,
            "ST_TOUCHES" => Self::StTouches,
            "ST_WITHIN" => Self::StWithin,
            "ST_BOUNDARY" => Self::StBoundary,
            "ST_BUFFER" => Self::StBuffer,
            "ST_BUFFERWITHTOLERANCE" => Self::StBufferwithtolerance,
            "ST_CLOSESTPOINT" => Self::StClosestpoint,
            "ST_CONVEXHULL" => Self::StConvexhull,
            "ST_DIFFERENCE" => Self::StDifference,
            "ST_INTERSECTION" => Self::StIntersection,
            "ST_SIMPLIFY" => Self::StSimplify,
            "ST_SNAPTOGRID" => Self::StSnaptogrid,
            "ST_UNION" => Self::StUnion,
            "ST_BOUNDINGBOX" => Self::StBoundingbox,
            "ST_GEOHASH" => Self::StGeohash,
            "ST_GEOGPOINTFROMGEOHASH" => Self::StGeogpointfromgeohash,

            "NET.IP_FROM_STRING" | "NET_IP_FROM_STRING" => Self::NetIpFromString,
            "NET.SAFE_IP_FROM_STRING" | "NET_SAFE_IP_FROM_STRING" => Self::NetSafeIpFromString,
            "NET.IPV4_FROM_INT64" | "NET_IPV4_FROM_INT64" => Self::NetIpv4FromInt64,
            "NET.IP_NET_MASK" | "NET_IP_NET_MASK" => Self::NetIpNetMask,
            "NET.IP_TRUNC" | "NET_IP_TRUNC" => Self::NetIpTrunc,
            "NET.IPV4_TO_INT64" | "NET_IPV4_TO_INT64" => Self::NetIpv4ToInt64,
            "NET.IP_TO_STRING" | "NET_IP_TO_STRING" => Self::NetIpToString,
            "NET.HOST" | "NET_HOST" => Self::NetHost,
            "NET.PUBLIC_SUFFIX" | "NET_PUBLIC_SUFFIX" => Self::NetPublicSuffix,
            "NET.REG_DOMAIN" | "NET_REG_DOMAIN" => Self::NetRegDomain,
            "NET.IP_IN_NET" | "NET_IP_IN_NET" => Self::NetIpInNet,
            "NET.MAKE_NET" | "NET_MAKE_NET" => Self::NetMakeNet,
            "NET.IP_IS_PRIVATE" | "NET_IP_IS_PRIVATE" => Self::NetIpIsPrivate,

            "KEYS.KEYSET_CHAIN" | "KEYS_KEYSET_CHAIN" => Self::KeysKeysetChain,
            "AEAD.ENCRYPT" | "AEAD_ENCRYPT" => Self::AeadEncrypt,
            "DETERMINISTIC_ENCRYPT" => Self::DeterministicEncrypt,
            "AEAD.DECRYPT_BYTES" | "AEAD_DECRYPT_BYTES" => Self::AeadDecryptBytes,
            "DETERMINISTIC_DECRYPT_BYTES" => Self::DeterministicDecryptBytes,
            "AEAD.DECRYPT_STRING" | "AEAD_DECRYPT_STRING" => Self::AeadDecryptString,
            "DETERMINISTIC_DECRYPT_STRING" => Self::DeterministicDecryptString,

            "ERROR" => Self::Error,
            "SESSION_USER" => Self::SessionUser,
            "CURRENT_USER" => Self::CurrentUser,
            "ARRAY" => Self::Array,
            "STRUCT" => Self::Struct,

            _ => Self::Custom(s.to_string()),
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Count => "COUNT",
            Self::Sum => "SUM",
            Self::Avg => "AVG",
            Self::Min => "MIN",
            Self::Max => "MAX",
            Self::AnyValue => "ANY_VALUE",

            Self::StringAgg => "STRING_AGG",
            Self::ArrayAgg => "ARRAY_AGG",
            Self::CountIf => "COUNTIF",

            Self::StddevPop => "STDDEV_POP",
            Self::StddevSamp => "STDDEV_SAMP",
            Self::Stddev => "STDDEV",
            Self::VarPop => "VAR_POP",
            Self::VarSamp => "VAR_SAMP",
            Self::Variance => "VARIANCE",
            Self::Corr => "CORR",
            Self::CovarPop => "COVAR_POP",
            Self::CovarSamp => "COVAR_SAMP",

            Self::LogicalAnd => "LOGICAL_AND",
            Self::LogicalOr => "LOGICAL_OR",
            Self::BitAnd => "BIT_AND",
            Self::BitOr => "BIT_OR",
            Self::BitXor => "BIT_XOR",

            Self::ApproxCountDistinct => "APPROX_COUNT_DISTINCT",
            Self::ApproxQuantiles => "APPROX_QUANTILES",
            Self::ApproxTopCount => "APPROX_TOP_COUNT",
            Self::ApproxTopSum => "APPROX_TOP_SUM",

            Self::HllCountInit => "HLL_COUNT.INIT",
            Self::HllCountMerge => "HLL_COUNT.MERGE",
            Self::HllCountMergePartial => "HLL_COUNT.MERGE_PARTIAL",
            Self::HllCountExtract => "HLL_COUNT.EXTRACT",

            Self::RowNumber => "ROW_NUMBER",
            Self::Rank => "RANK",
            Self::DenseRank => "DENSE_RANK",
            Self::Ntile => "NTILE",
            Self::PercentRank => "PERCENT_RANK",
            Self::CumeDist => "CUME_DIST",
            Self::Lag => "LAG",
            Self::Lead => "LEAD",
            Self::FirstValue => "FIRST_VALUE",
            Self::LastValue => "LAST_VALUE",
            Self::NthValue => "NTH_VALUE",
            Self::PercentileCont => "PERCENTILE_CONT",
            Self::PercentileDisc => "PERCENTILE_DISC",

            Self::Upper => "UPPER",
            Self::Lower => "LOWER",
            Self::Trim => "TRIM",
            Self::Ltrim => "LTRIM",
            Self::Rtrim => "RTRIM",
            Self::Concat => "CONCAT",
            Self::Substr => "SUBSTR",
            Self::Substring => "SUBSTRING",
            Self::Length => "LENGTH",
            Self::CharLength => "CHAR_LENGTH",
            Self::CharacterLength => "CHARACTER_LENGTH",
            Self::OctetLength => "OCTET_LENGTH",
            Self::ByteLength => "BYTE_LENGTH",
            Self::Position => "POSITION",
            Self::Strpos => "STRPOS",
            Self::Instr => "INSTR",
            Self::Replace => "REPLACE",
            Self::Split => "SPLIT",
            Self::Reverse => "REVERSE",
            Self::Repeat => "REPEAT",
            Self::Left => "LEFT",
            Self::Right => "RIGHT",
            Self::Lpad => "LPAD",
            Self::Rpad => "RPAD",
            Self::Ascii => "ASCII",
            Self::Chr => "CHR",
            Self::Initcap => "INITCAP",
            Self::Translate => "TRANSLATE",
            Self::Format => "FORMAT",
            Self::Normalize => "NORMALIZE",
            Self::NormalizeAndCasefold => "NORMALIZE_AND_CASEFOLD",
            Self::RegexpContains => "REGEXP_CONTAINS",
            Self::RegexpReplace => "REGEXP_REPLACE",
            Self::RegexpExtract => "REGEXP_EXTRACT",
            Self::RegexpExtractAll => "REGEXP_EXTRACT_ALL",
            Self::RegexpInstr => "REGEXP_INSTR",
            Self::RegexpSubstr => "REGEXP_SUBSTR",
            Self::StartsWith => "STARTS_WITH",
            Self::EndsWith => "ENDS_WITH",
            Self::ContainsSubstr => "CONTAINS_SUBSTR",
            Self::SafeConvertBytesToString => "SAFE_CONVERT_BYTES_TO_STRING",
            Self::CodePointsToBytes => "CODE_POINTS_TO_BYTES",
            Self::CodePointsToString => "CODE_POINTS_TO_STRING",
            Self::ToCodePoints => "TO_CODE_POINTS",
            Self::ToBase32 => "TO_BASE32",
            Self::ToBase64 => "TO_BASE64",
            Self::ToHex => "TO_HEX",
            Self::Soundex => "SOUNDEX",
            Self::Unicode => "UNICODE",

            Self::Abs => "ABS",
            Self::Ceil => "CEIL",
            Self::Ceiling => "CEILING",
            Self::Floor => "FLOOR",
            Self::Round => "ROUND",
            Self::Trunc => "TRUNC",
            Self::Sqrt => "SQRT",
            Self::Pow => "POW",
            Self::Power => "POWER",
            Self::Exp => "EXP",
            Self::Ln => "LN",
            Self::Log => "LOG",
            Self::Log10 => "LOG10",
            Self::Sign => "SIGN",
            Self::Mod => "MOD",
            Self::Div => "DIV",
            Self::Rand => "RAND",
            Self::Pi => "PI",
            Self::Greatest => "GREATEST",
            Self::Least => "LEAST",
            Self::IsInf => "IS_INF",
            Self::IsNan => "IS_NAN",
            Self::IeeeDivide => "IEEE_DIVIDE",
            Self::SafeDivide => "SAFE_DIVIDE",
            Self::SafeMultiply => "SAFE_MULTIPLY",
            Self::SafeAdd => "SAFE_ADD",
            Self::SafeSubtract => "SAFE_SUBTRACT",
            Self::SafeNegate => "SAFE_NEGATE",
            Self::RangeBucket => "RANGE_BUCKET",

            Self::Sin => "SIN",
            Self::Cos => "COS",
            Self::Tan => "TAN",
            Self::Asin => "ASIN",
            Self::Acos => "ACOS",
            Self::Atan => "ATAN",
            Self::Atan2 => "ATAN2",
            Self::Sinh => "SINH",
            Self::Cosh => "COSH",
            Self::Tanh => "TANH",
            Self::Asinh => "ASINH",
            Self::Acosh => "ACOSH",
            Self::Atanh => "ATANH",
            Self::Cot => "COT",
            Self::Coth => "COTH",
            Self::Sec => "SEC",
            Self::Sech => "SECH",
            Self::Csc => "CSC",
            Self::Csch => "CSCH",
            Self::Cbrt => "CBRT",

            Self::CurrentDate => "CURRENT_DATE",
            Self::CurrentDatetime => "CURRENT_DATETIME",
            Self::CurrentTime => "CURRENT_TIME",
            Self::CurrentTimestamp => "CURRENT_TIMESTAMP",
            Self::Extract => "EXTRACT",

            Self::Date => "DATE",
            Self::DateAdd => "DATE_ADD",
            Self::DateDiff => "DATE_DIFF",
            Self::DateSub => "DATE_SUB",
            Self::DateTrunc => "DATE_TRUNC",
            Self::DateFromUnixDate => "DATE_FROM_UNIX_DATE",

            Self::Datetime => "DATETIME",
            Self::DatetimeAdd => "DATETIME_ADD",
            Self::DatetimeDiff => "DATETIME_DIFF",
            Self::DatetimeSub => "DATETIME_SUB",
            Self::DatetimeTrunc => "DATETIME_TRUNC",

            Self::Time => "TIME",
            Self::TimeAdd => "TIME_ADD",
            Self::TimeDiff => "TIME_DIFF",
            Self::TimeSub => "TIME_SUB",
            Self::TimeTrunc => "TIME_TRUNC",

            Self::Timestamp => "TIMESTAMP",
            Self::TimestampAdd => "TIMESTAMP_ADD",
            Self::TimestampDiff => "TIMESTAMP_DIFF",
            Self::TimestampSub => "TIMESTAMP_SUB",
            Self::TimestampTrunc => "TIMESTAMP_TRUNC",
            Self::TimestampMicros => "TIMESTAMP_MICROS",
            Self::TimestampMillis => "TIMESTAMP_MILLIS",
            Self::TimestampSeconds => "TIMESTAMP_SECONDS",

            Self::UnixDate => "UNIX_DATE",
            Self::UnixMicros => "UNIX_MICROS",
            Self::UnixMillis => "UNIX_MILLIS",
            Self::UnixSeconds => "UNIX_SECONDS",

            Self::FormatDate => "FORMAT_DATE",
            Self::FormatDatetime => "FORMAT_DATETIME",
            Self::FormatTime => "FORMAT_TIME",
            Self::FormatTimestamp => "FORMAT_TIMESTAMP",

            Self::ParseDate => "PARSE_DATE",
            Self::ParseDatetime => "PARSE_DATETIME",
            Self::ParseTime => "PARSE_TIME",
            Self::ParseTimestamp => "PARSE_TIMESTAMP",

            Self::MakeDate => "MAKE_DATE",
            Self::MakeInterval => "MAKE_INTERVAL",
            Self::MakeTime => "MAKE_TIME",
            Self::MakeTimestamp => "MAKE_TIMESTAMP",
            Self::LastDay => "LAST_DAY",

            Self::IntervalParse => "INTERVAL_PARSE",

            Self::Coalesce => "COALESCE",
            Self::Nullif => "NULLIF",
            Self::Ifnull => "IFNULL",
            Self::If => "IF",

            Self::Cast => "CAST",
            Self::SafeCast => "SAFE_CAST",

            Self::JsonExtract => "JSON_EXTRACT",
            Self::JsonExtractScalar => "JSON_EXTRACT_SCALAR",
            Self::JsonValue => "JSON_VALUE",
            Self::JsonQuery => "JSON_QUERY",
            Self::JsonType => "JSON_TYPE",
            Self::JsonExtractArray => "JSON_EXTRACT_ARRAY",
            Self::JsonExtractStringArray => "JSON_EXTRACT_STRING_ARRAY",
            Self::JsonQueryArray => "JSON_QUERY_ARRAY",
            Self::JsonValueArray => "JSON_VALUE_ARRAY",
            Self::ParseJson => "PARSE_JSON",
            Self::ToJson => "TO_JSON",
            Self::ToJsonString => "TO_JSON_STRING",
            Self::LaxBool => "LAX_BOOL",
            Self::LaxInt64 => "LAX_INT64",
            Self::LaxFloat64 => "LAX_FLOAT64",
            Self::LaxString => "LAX_STRING",
            Self::JsonBool => "BOOL",
            Self::JsonInt64 => "INT64",
            Self::JsonFloat64 => "FLOAT64",
            Self::JsonString => "STRING",

            Self::ArrayLength => "ARRAY_LENGTH",
            Self::ArrayConcat => "ARRAY_CONCAT",
            Self::ArrayReverse => "ARRAY_REVERSE",
            Self::ArrayToString => "ARRAY_TO_STRING",
            Self::GenerateArray => "GENERATE_ARRAY",
            Self::GenerateDateArray => "GENERATE_DATE_ARRAY",
            Self::GenerateTimestampArray => "GENERATE_TIMESTAMP_ARRAY",
            Self::ArrayFilter => "ARRAY_FILTER",
            Self::ArrayTransform => "ARRAY_TRANSFORM",
            Self::ArrayIncludes => "ARRAY_INCLUDES",
            Self::ArrayIncludesAny => "ARRAY_INCLUDES_ANY",
            Self::ArrayIncludesAll => "ARRAY_INCLUDES_ALL",
            Self::Offset => "OFFSET",
            Self::Ordinal => "ORDINAL",
            Self::SafeOffset => "SAFE_OFFSET",
            Self::SafeOrdinal => "SAFE_ORDINAL",
            Self::Unnest => "UNNEST",

            Self::GenerateUuid => "GENERATE_UUID",
            Self::Md5 => "MD5",
            Self::Sha1 => "SHA1",
            Self::Sha256 => "SHA256",
            Self::Sha512 => "SHA512",
            Self::FarmFingerprint => "FARM_FINGERPRINT",
            Self::FromHex => "FROM_HEX",
            Self::FromBase64 => "FROM_BASE64",

            Self::StGeogpoint => "ST_GEOGPOINT",
            Self::StGeogfromtext => "ST_GEOGFROMTEXT",
            Self::StGeogfromgeojson => "ST_GEOGFROMGEOJSON",
            Self::StAstext => "ST_ASTEXT",
            Self::StAsgeojson => "ST_ASGEOJSON",
            Self::StAsbinary => "ST_ASBINARY",
            Self::StX => "ST_X",
            Self::StY => "ST_Y",
            Self::StGeometrytype => "ST_GEOMETRYTYPE",
            Self::StIsempty => "ST_ISEMPTY",
            Self::StIsclosed => "ST_ISCLOSED",
            Self::StIscollection => "ST_ISCOLLECTION",
            Self::StDimension => "ST_DIMENSION",
            Self::StNumpoints => "ST_NUMPOINTS",
            Self::StNpoints => "ST_NPOINTS",
            Self::StPointn => "ST_POINTN",
            Self::StStartpoint => "ST_STARTPOINT",
            Self::StEndpoint => "ST_ENDPOINT",
            Self::StMakeline => "ST_MAKELINE",
            Self::StMakepolygon => "ST_MAKEPOLYGON",
            Self::StDistance => "ST_DISTANCE",
            Self::StLength => "ST_LENGTH",
            Self::StArea => "ST_AREA",
            Self::StPerimeter => "ST_PERIMETER",
            Self::StMaxdistance => "ST_MAXDISTANCE",
            Self::StAzimuth => "ST_AZIMUTH",
            Self::StCentroid => "ST_CENTROID",
            Self::StContains => "ST_CONTAINS",
            Self::StCovers => "ST_COVERS",
            Self::StCoveredby => "ST_COVEREDBY",
            Self::StDisjoint => "ST_DISJOINT",
            Self::StDwithin => "ST_DWITHIN",
            Self::StEquals => "ST_EQUALS",
            Self::StIntersects => "ST_INTERSECTS",
            Self::StTouches => "ST_TOUCHES",
            Self::StWithin => "ST_WITHIN",
            Self::StBoundary => "ST_BOUNDARY",
            Self::StBuffer => "ST_BUFFER",
            Self::StBufferwithtolerance => "ST_BUFFERWITHTOLERANCE",
            Self::StClosestpoint => "ST_CLOSESTPOINT",
            Self::StConvexhull => "ST_CONVEXHULL",
            Self::StDifference => "ST_DIFFERENCE",
            Self::StIntersection => "ST_INTERSECTION",
            Self::StSimplify => "ST_SIMPLIFY",
            Self::StSnaptogrid => "ST_SNAPTOGRID",
            Self::StUnion => "ST_UNION",
            Self::StBoundingbox => "ST_BOUNDINGBOX",
            Self::StGeohash => "ST_GEOHASH",
            Self::StGeogpointfromgeohash => "ST_GEOGPOINTFROMGEOHASH",

            Self::NetIpFromString => "NET.IP_FROM_STRING",
            Self::NetSafeIpFromString => "NET.SAFE_IP_FROM_STRING",
            Self::NetIpv4FromInt64 => "NET.IPV4_FROM_INT64",
            Self::NetIpNetMask => "NET.IP_NET_MASK",
            Self::NetIpTrunc => "NET.IP_TRUNC",
            Self::NetIpv4ToInt64 => "NET.IPV4_TO_INT64",
            Self::NetIpToString => "NET.IP_TO_STRING",
            Self::NetHost => "NET.HOST",
            Self::NetPublicSuffix => "NET.PUBLIC_SUFFIX",
            Self::NetRegDomain => "NET.REG_DOMAIN",
            Self::NetIpInNet => "NET.IP_IN_NET",
            Self::NetMakeNet => "NET.MAKE_NET",
            Self::NetIpIsPrivate => "NET.IP_IS_PRIVATE",

            Self::KeysKeysetChain => "KEYS.KEYSET_CHAIN",
            Self::AeadEncrypt => "AEAD.ENCRYPT",
            Self::DeterministicEncrypt => "DETERMINISTIC_ENCRYPT",
            Self::AeadDecryptBytes => "AEAD.DECRYPT_BYTES",
            Self::DeterministicDecryptBytes => "DETERMINISTIC_DECRYPT_BYTES",
            Self::AeadDecryptString => "AEAD.DECRYPT_STRING",
            Self::DeterministicDecryptString => "DETERMINISTIC_DECRYPT_STRING",

            Self::Error => "ERROR",
            Self::SessionUser => "SESSION_USER",
            Self::CurrentUser => "CURRENT_USER",
            Self::Array => "ARRAY",
            Self::Struct => "STRUCT",

            Self::Custom(s) => s,
        }
    }

    pub fn is_aggregate(&self) -> bool {
        matches!(
            self,
            Self::Count
                | Self::Sum
                | Self::Avg
                | Self::Min
                | Self::Max
                | Self::AnyValue
                | Self::StringAgg
                | Self::ArrayAgg
                | Self::CountIf
                | Self::StddevPop
                | Self::StddevSamp
                | Self::Stddev
                | Self::VarPop
                | Self::VarSamp
                | Self::Variance
                | Self::Corr
                | Self::CovarPop
                | Self::CovarSamp
                | Self::LogicalAnd
                | Self::LogicalOr
                | Self::BitAnd
                | Self::BitOr
                | Self::BitXor
                | Self::ApproxCountDistinct
                | Self::ApproxQuantiles
                | Self::ApproxTopCount
                | Self::ApproxTopSum
                | Self::HllCountInit
                | Self::HllCountMerge
                | Self::HllCountMergePartial
                | Self::HllCountExtract
        )
    }

    pub fn is_window(&self) -> bool {
        matches!(
            self,
            Self::RowNumber
                | Self::Rank
                | Self::DenseRank
                | Self::Ntile
                | Self::PercentRank
                | Self::CumeDist
                | Self::Lag
                | Self::Lead
                | Self::FirstValue
                | Self::LastValue
                | Self::NthValue
                | Self::PercentileCont
                | Self::PercentileDisc
        )
    }

    pub fn is_scalar(&self) -> bool {
        !self.is_aggregate() && !self.is_window()
    }
}

impl std::fmt::Display for FunctionName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl From<&str> for FunctionName {
    fn from(s: &str) -> Self {
        Self::parse(s)
    }
}

impl From<String> for FunctionName {
    fn from(s: String) -> Self {
        Self::parse(&s)
    }
}
